// generated by brust v2 — client chunk for input_ba5f4ec9
import { signal, computed, defineBehavior } from "brust/runtime-dom"
const __attr = (v) => (v === false ? null : v)
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("input_ba5f4ec9", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const picked = signal(null)
  const _h1 = (r, ...a) => (() => picked.set(r.id))(...a)
  const _l1 = computed(() => props().rows)
  const _k1 = (r) => r.id
  const _c1 = (r) => __attr(r.id === picked() ? "on" : "")
  const _c2 = (r) => __text(r.name)
  return { picked, _h1, _l1, _k1, _c1, _c2 }
})
