import { writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { BunPlugin } from 'bun'
import type { ScanActionsResult } from '../scan-actions.ts'

/** Write a TypeScript file that re-exports `scanActions` as a pure function
 * returning a hard-coded ActionDef[]. Bundle this file via `actionsPrebuiltPlugin`
 * below to satisfy `import { scanActions } from './scan-actions.ts'` lookups
 * inside the runtime bundle without walking the filesystem at runtime.
 *
 * `idToSourcePath` maps each discovered action id → absolute path of the
 * `'use server'` file it was exported from. The orchestrator builds this map
 * by calling `collectExports(sourceFile)` for every file in `scan.sourceFiles`.
 *
 * `repoRoot` is the absolute path of the brust repo (where `runtime/` lives).
 * `outPath` is where to write the generated file (e.g. <outDir>/_actions-prebuilt.ts).
 */
export async function writePrebuiltActionsFileWithMap(
  outPath: string,
  idToSourcePath: Map<string, string>,
  repoRoot: string,
): Promise<void> {
  const actionsPath = resolve(repoRoot, 'runtime/actions.ts')
  const scanPath = resolve(repoRoot, 'runtime/scan-actions.ts')

  // Stable file order = stable import order = deterministic builds.
  const filePaths = [...new Set(idToSourcePath.values())].sort()
  const fileToVar = new Map<string, string>()
  filePaths.forEach((p, i) => fileToVar.set(p, `__mod${i}`))

  const imports = filePaths
    .map((p, i) => `import * as __mod${i} from ${JSON.stringify(p)}`)
    .join('\n')

  const sortedIds = [...idToSourcePath.keys()].sort((a, b) => a.localeCompare(b))
  const entries = sortedIds
    .map((id) => {
      const v = fileToVar.get(idToSourcePath.get(id)!)!
      const key = JSON.stringify(id)
      return `  { id: ${key}, fn: (${v}[${key}] as any), middleware: getActionMiddleware(${v}[${key}]) }`
    })
    .join(',\n')

  const src = `// AUTO-GENERATED by brust build — do not edit.
import { getActionMiddleware } from ${JSON.stringify(actionsPath)}
import type { ActionDef } from ${JSON.stringify(actionsPath)}
import type { ScanOptions, ScanActionsResult } from ${JSON.stringify(scanPath)}
${imports}

// Re-export auxiliaries so any bundle import from scan-actions.ts still resolves.
export { stripLeadingTrivia, hasUseServerDirective, collectExports } from ${JSON.stringify(scanPath)}
export type { ScanOptions, ScanActionsResult } from ${JSON.stringify(scanPath)}

const PREBUILT: ActionDef[] = [
${entries}
]

export async function scanActions(_opts: ScanOptions = {}): Promise<ScanActionsResult> {
  return { actions: PREBUILT, sourceFiles: [] }
}
`
  await writeFile(outPath, src, 'utf-8')
}

/** Bun.build plugin that aliases `runtime/scan-actions.ts` to the generated
 * prebuilt file. Combined with `writePrebuiltActionsFileWithMap` this makes
 * the bundled `scanActions()` return a hard-coded list. */
export function actionsPrebuiltPlugin(
  generatedFilePath: string,
  repoRoot: string,
): BunPlugin {
  const targetPath = resolve(repoRoot, 'runtime/scan-actions.ts')

  return {
    name: 'brust-actions-prebuilt',
    setup(build) {
      build.onResolve({ filter: /.*/ }, (args) => {
        // Match the canonical scan-actions.ts file regardless of how it's
        // imported (relative './scan-actions.ts' from runtime/index.ts, etc.).
        // Resolve the import to an absolute path and compare.
        const resolved = resolve(args.importer ? args.importer.replace(/\/[^/]*$/, '') : repoRoot, args.path)
        if (resolved === targetPath || resolved + '.ts' === targetPath) {
          return { path: generatedFilePath }
        }
        // Default resolution for everything else.
        return undefined
      })
    },
  }
}
