// Generated by scripts/build/jsonByteClass.ts at configure time. Do not
// edit. The same definition feeds the Highway JSON kernel (these nibble
// LUTs) and the Rust scalar indexer (the derived 256-entry table); see
// the generator for why they must agree byte for byte.
//
// cls = LUT_LO[b & 0xF] & LUT_HI[b >> 4]
//   0x07 structural { } [ ] : ,    0x18 whitespace sp \t \n \r
//   0x20 oddity / '                0x40 control < 0x20

#pragma once
#include <stdint.h>

#define BUN_JSON_CLASS_STRUCTURAL 0x07
#define BUN_JSON_CLASS_WHITESPACE 0x18
#define BUN_JSON_CLASS_ODDITY 0x20
#define BUN_JSON_CLASS_CONTROL 0x40

alignas(16) static const uint8_t kBunJsonLutLo[16] = { 0x50, 0x40, 0x40, 0x40, 0x40, 0x40, 0x40, 0x60, 0x40, 0x48, 0x4c, 0x41, 0x42, 0x49, 0x40, 0x60 };
alignas(16) static const uint8_t kBunJsonLutHi[16] = { 0x48, 0x40, 0x32, 0x04, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
