// Generated by scripts/build/xmlByteClass.ts at configure time. Do not
// edit. The same definition feeds the Highway XML kernel (these nibble
// LUTs) and the Rust scalar indexer (the derived 256-entry table).
//
// cls = LUT_LO[b & 0xF] & LUT_HI[b >> 4]
//   0x07 always  & \r control     0x38 tag  \t \n " ' =
//   0x40 <                        0x80 >

#pragma once
#include <stdint.h>

#define BUN_XML_CLASS_ALWAYS 0x07
#define BUN_XML_CLASS_TAG 0x38
#define BUN_XML_CLASS_LT 0x40
#define BUN_XML_CLASS_GT 0x80

alignas(16) static const uint8_t kBunXmlLutLo[16] = { 0x03, 0x03, 0x13, 0x03, 0x03, 0x03, 0x07, 0x13, 0x03, 0x0a, 0x0a, 0x03, 0x43, 0x23, 0x83, 0x03 };
alignas(16) static const uint8_t kBunXmlLutHi[16] = { 0x09, 0x02, 0x14, 0xe0, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
