// generated by brust v2 — client chunk for input_a93faba9
import { signal, computed, defineBehavior } from "brust/runtime-dom"
import { fmt } from "./money"
export default defineBehavior("input_a93faba9", ({ el, props, effect, onCleanup, ref }) => {
  const scale = signal(2)
  const _h1 = (...a) => (() => scale.set(scale() + 1))(...a)
  const _l1 = computed(() => props().rows)
  const _k1 = (row) => row.id
  const _l2 = (row) => row.cells
  const _k2 = (c) => c
  const _c1 = (c) => fmt(c * scale(), props().unit)
  const _c2 = (ri) => ri
  return { scale, _h1, _l1, _k1, _l2, _k2, _c1, _c2 }
})
