// generated by brust v2 — precompute job for input_a93faba9; pure function of its inputs
import { fmt } from "./money"
export const inputs = ["rows", "unit"] as const
export function precompute(props: any) {
  const { rows, unit } = props
  const scale = 2
  return { _s1: (rows).map((row, ri) => (row.cells).map((c) => fmt(c * scale, unit))) }
}
