// generated by brust v2 — precompute job for input_f3d26057; pure function of its inputs
import { fmt } from "./money"
export const inputs = ["a", "b", "items", "n", "show"] as const
export function precompute(props: any) {
  const { a, b, items, n, show } = props
  const open = false
  return { _s1: ((show) ? fmt(n) : null), _s2: ((open) ? fmt(n * 2) : null), _s3: (items).map((it) => ((it.sale) ? fmt(it.price) : null)), _s4: ((a && b) ? fmt(n + 1) : null) }
}
