// generated by brust v2 — client chunk for input_f3d26057
import { signal, computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_f3d26057", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const open = signal(false)
  const _h1 = (...a) => (() => open.set(!open()))(...a)
  const _c1 = computed(() => props().show)
  const _c2 = computed(() => open())
  const _c3 = computed(() => props().a && props().b)
  return { open, _h1, _c1, _c2, _c3 }
})
