// @ts-ignore - index.js is generated by napi-rs at build time; may not exist during type-check
import * as native from './index.js'

export interface ServeOptions {
  port: number
  workers: number
  entry: string
  bootTimeoutMs?: number
}

// Render callback writes HTML bytes into the worker's pre-registered SharedArrayBuffer
// (passed once at register time) and resolves with the number of bytes written.
// The argument is a JSON envelope `{ route_id, path, params }` produced by Rust's
// route table — not a raw path. See runtime/routes.ts::RouteCall.
// Resolve 0 → Rust treats it as oversized/error and returns HTTP 500.
export type RenderFn = (envelopeJson: string) => Promise<number>

// Bun Workers run in the same OS process as the main thread; the `env` option
// only patches the JS-visible process.env, not the native OS environment that
// Rust reads via std::env::var.  Read the flag here in JS instead.
export const isWorker: boolean = process.env.BRUST_WORKER_ID !== undefined

// native.workerId() reads a thread-local set by registerRenderer, so it must
// be re-evaluated at the point of use (not cached at module load).
export function workerId(): number | null {
  return (native as any).workerId()
}

export const brust = {
  async serve(opts: ServeOptions): Promise<void> {
    ; (native as any).beginServe({
      port: opts.port,
      workers: opts.workers,
      entry: opts.entry,
    })
    for (let i = 0; i < opts.workers; i++) {
      // Bun.Worker requires the JS entry (post-bundling). For the skeleton,
      // the entry is a TS file that Bun executes directly.
      new Worker(opts.entry, {
        env: { ...process.env, BRUST_WORKER_ID: String(i) },
      })
    }
    // Bun Workers intercept SIGINT before Rust's ctrl_c() handler fires.
    // Install a JS-level handler so the process actually exits on SIGINT.
    process.on('SIGINT', () => process.exit(0))
    await (native as any).untilReady(opts.bootTimeoutMs ?? 5000)
    await (native as any).untilShutdown()
  },
  /** Install the route table in Rust. MUST be called before `serve()`. */
  registerRoutes(patterns: string[]): number {
    return (native as any).registerRoutes(patterns)
  },
  // Register a renderer for this Bun Worker. `buf` MUST be backed by a SharedArrayBuffer
  // (or any ArrayBuffer the worker keeps rooted) — Rust captures the backing-store
  // pointer once here and reuses it for every render call. The buffer is held alive
  // by the worker's module scope; do not let it go out of scope.
  registerRenderer(buf: Uint8Array, fn: RenderFn): number {
    return (native as any).registerRenderer(buf, fn)
  },
}

export { defineRoutes, makeRenderer } from './routes.ts'
export type { Route, RouteCall, RouteContext, ErrorBoundaryProps } from './routes.ts'
