// @ts-ignore - index.js is generated by napi-rs at build time; may not exist during type-check
import * as native from './index.js'
import type { ActionDef } from './actions.ts'
import { isValidActionId } from './actions.ts'

export interface ServeOptions {
  port: number
  workers: number
  entry: string
  bootTimeoutMs?: number
  /** Action definitions discovered by `brust.scanActions()`. When present,
   * `serve` calls the internal action registry before the listener binds.
   * Optional — omit if the app has no server actions. */
  actions?: ActionDef[]
  /** MCP support — pass a manifest built via brust.buildMcpManifest. brust.serve
   * does NOT auto-wire MCP into workers; the worker branch of the entry file must
   * call brust.loadMcpManifest() + makeMcpServer() itself and pass the McpServer
   * to makeRenderer via `opts.mcp`. See example/hello-world/index.ts for the
   * pattern. The field here is currently unused inside serve() and is reserved
   * for future IPC-based propagation of the manifest. */
  mcp?: { manifest: import('./mcp/manifest.ts').McpManifest }
}

// Render callback. The body bytes flow through `napi.renderChunk(workerId, len)`
// — one or more Bytes chunks followed by a Final chunk (len=0). The returned
// Promise just signals "renderer callback returned" so Rust's dispatch loop
// can fall through to terminator/cleanup. The argument is a JSON envelope
// `{ route_id, path, params }` produced by Rust's route table — see
// runtime/routes.ts::RouteCall.
export type RenderFn = (envelopeJson: string) => Promise<void>

// Bun Workers run in the same OS process as the main thread; the `env` option
// only patches the JS-visible process.env, not the native OS environment that
// Rust reads via std::env::var.  Read the flag here in JS instead.
export const isWorker: boolean = process.env.BRUST_WORKER_ID !== undefined

// native.workerId() reads a thread-local set by registerRenderer, so it must
// be re-evaluated at the point of use (not cached at module load).
export function workerId(): number | null {
  return (native as any).workerId()
}

function registerActionsInternal(actions: Array<{ id: string }>): number {
  const seen = new Set<string>()
  for (const a of actions) {
    if (!isValidActionId(a.id)) {
      throw new Error(
        `action id ${JSON.stringify(a.id)} contains invalid characters; ` +
        `allowed: [A-Za-z0-9_-]+ (max 128 chars)`,
      )
    }
    if (seen.has(a.id)) {
      throw new Error(`action id ${JSON.stringify(a.id)} registered more than once`)
    }
    seen.add(a.id)
  }
  return (native as any).registerActions(actions.map((a) => a.id))
}

export const brust = {
  async serve(opts: ServeOptions): Promise<void> {
    if (opts.actions && opts.actions.length > 0) {
      // Register action ids with Rust. registerActionsInternal validates
      // charset + uniqueness; throws on either. Mirrors the previous
      // `brust.registerActions` user-facing call exactly.
      registerActionsInternal(opts.actions)
    }
    ; (native as any).beginServe({
      port: opts.port,
      workers: opts.workers,
      entry: opts.entry,
    })
    for (let i = 0; i < opts.workers; i++) {
      // Bun.Worker requires the JS entry (post-bundling). For the skeleton,
      // the entry is a TS file that Bun executes directly.
      new Worker(opts.entry, {
        env: { ...process.env, BRUST_WORKER_ID: String(i) },
      })
    }
    // Bun Workers intercept SIGINT before Rust's ctrl_c() handler fires.
    // Install a JS-level handler so the process actually exits on SIGINT.
    process.on('SIGINT', () => process.exit(0))
    await (native as any).untilReady(opts.bootTimeoutMs ?? 5000)
    await (native as any).untilShutdown()
  },
  /** Install the route table in Rust. MUST be called before `serve()`.
   * Pass an array of FlatRoutes from `defineRoutes(...)` — each is JSON-encoded
   * with its optional cache config. Rust matches against `fullPath`. */
  registerRoutes(routes: import('./routes.ts').FlatRoute[]): number {
    const configs = routes.map((r) => JSON.stringify({ path: r.fullPath, cache: r.cache ?? null }))
    return (native as any).registerRoutes(configs)
  },
  /** Register the list of literal route paths that should be dispatched as
   * SSE (text/event-stream) instead of going through the render pipeline.
   * Call from the main process after defineRoutes — the worker only needs
   * the call if it also accepts SSE traffic, but in the current model the
   * main accept loop owns dispatch so this is main-only. MVP supports only
   * literal paths; parameterized routes (e.g. `/sse/{room}`) are a follow-up. */
  registerSsePaths(paths: string[]): void {
    ; (native as any).napiRegisterSsePaths(paths)
  },
  /** Register the list of literal route paths that should be dispatched as
   * WebSocket upgrades. Call from the main process after defineRoutes.
   * MVP supports only literal paths — parameterized routes (e.g.
   * `/ws/chat/{room}`) are a follow-up. */
  registerWsPaths(paths: string[]): void {
    ;(native as any).napiRegisterWsPaths(paths)
  },
  /** Set the response cache capacity (entries). Default is 1000.
   * Safe to call at any time; if shrinking below current size, excess
   * LRU entries are evicted. */
  configureCache(opts: { maxEntries: number }): void {
    ; (native as any).configureCache(opts.maxEntries)
  },
  /** Tell Rust where to read `/_brust/islands/<file>` from. Called once at
   * boot after buildIslands() emits chunks. Path must be absolute. */
  configureIslandsDir(dir: string): void {
    ; (native as any).configureIslandsDir(dir)
  },
  /** Walk the project for files marked `'use server'`, import them, and
   * return all named function exports as ActionDef[] plus the list of source
   * files (needed by brust.buildMcpManifest). Both the main process and each
   * worker should call this once at module top-level and pass `actions` to
   * `brust.serve({ actions, ... })` (main) and `makeRenderer(..., { actions,
   * ... })` (worker). See ScanOptions for roots / ignore overrides. */
  async scanActions(opts?: import('./scan-actions.ts').ScanOptions): Promise<import('./scan-actions.ts').ScanActionsResult> {
    const { scanActions } = await import('./scan-actions.ts')
    return scanActions(opts)
  },
  /** Extract the MCP manifest from TypeScript source using the compiler API,
   * write it to `.brust/mcp-manifest.json`, and return it. Call once in the
   * main process after `brust.registerRoutes(routes)`. Workers must read the
   * persisted manifest themselves via `brust.loadMcpManifest()` in the worker
   * branch and pass an `McpServer` (built via `makeMcpServer`) to
   * `makeRenderer` via `opts.mcp`. See example/hello-world/index.ts. */
  async buildMcpManifest(opts: {
    serverFiles: string[]
    routesFile: string
    sourceRoots: string[]
    actions: import('./actions.ts').ActionDef[]
    routes: import('./routes.ts').FlatRoute[]
    cwd?: string
  }): Promise<import('./mcp/manifest.ts').McpManifest> {
    const { extractMcpManifest } = await import('./mcp/extractor.ts')
    const { writeManifest } = await import('./mcp/manifest.ts')
    const m = await extractMcpManifest(opts)
    await writeManifest(opts.cwd ?? process.cwd(), m)
    return m
  },
  /** Read the MCP manifest from `.brust/mcp-manifest.json`. Returns null if
   * the file does not exist (i.e. the main process hasn't called
   * `brust.buildMcpManifest` yet). Throws if the file is malformed. */
  async loadMcpManifest(cwd: string = process.cwd()): Promise<import('./mcp/manifest.ts').McpManifest | null> {
    const { readManifest } = await import('./mcp/manifest.ts')
    return readManifest(cwd)
  },
  // Register a renderer for this Bun Worker. `buf` MUST be backed by a SharedArrayBuffer
  // (or any ArrayBuffer the worker keeps rooted) — Rust captures the backing-store
  // pointer once here and reuses it for every render call. The buffer is held alive
  // by the worker's module scope; do not let it go out of scope.
  registerRenderer(buf: Uint8Array, fn: RenderFn): number {
    return (native as any).registerRenderer(buf, fn)
  },
}

export { defineRoutes, makeRenderer, Outlet } from './routes.ts'
export type {
  Route,
  RouteCall,
  RouteContext,
  ErrorBoundaryProps,
  RouteCacheConfig,
  BrustRequest,
  RouteResponse,
  Middleware,
} from './routes.ts'

export { withMiddleware, isValidActionId } from './actions.ts'
export type { ActionDef, ActionFn } from './actions.ts'
export type { ScanOptions, ScanActionsResult } from './scan-actions.ts'

export { loadConfig, BrustConfigError } from './config.ts'
export type { BrustConfig } from './config.ts'

export { Island } from './islands/island.tsx'
export type { IslandProps, HydrateTrigger } from './islands/island.tsx'

export { buildIslands } from './islands/build.ts'
export type { IslandsBuildResult, IslandsConfig } from './islands/build.ts'
