import { createContext, createElement, useContext, type ComponentType, type ReactNode } from 'react'
import { Buffer } from 'node:buffer'
// @ts-ignore - index.js is generated by napi-rs at build time
import * as native from './index.js'
import { renderBranchStreaming } from './render/stream.ts'
import type { ActionDef } from './actions.ts'

// Permanently-unaborted AbortSignal sentinel for non-SSE routes.
// The controller is held in module scope and never .abort()-ed, keeping
// the signal alive in the unaborted state. Do NOT use AbortSignal.abort()
// — that creates an already-aborted signal which would fire any
// addEventListener('abort') listener synchronously and break defensive
// cleanup code.
const _neverAbortsController = new AbortController()
export const NEVER_ABORTS: AbortSignal = _neverAbortsController.signal

/** Structured view of the request, parsed once in Rust and shipped in the
 * JSON envelope. Header names are lower-cased. Cookies are parsed from the
 * Cookie header. `search` is the query string parsed as key→value (last
 * occurrence wins on duplicates). */
export interface BrustRequest {
  method: string
  /** Full request URL path including query string, e.g. `/foo?bar=1`. */
  url: string
  headers: Record<string, string>
  cookies: Record<string, string>
  search: Record<string, string>
  /** AbortSignal that fires when the client disconnects mid-request.
   * SSE-only in MVP — non-SSE routes receive NEVER_ABORTS (a permanently-
   * unaborted shared sentinel; signal.aborted === false forever). Real
   * disconnect detection for render/action is a follow-up. */
  signal: AbortSignal
}

/** Handler module shape — what `() => Promise<WsHandlers>` resolves to.
 *  open/message/close are all OPTIONAL — a no-op WebSocket (handshake
 *  only, e.g. liveness probe) is a valid use case. */
export interface WsHandlers {
  /** Called once after the 101 handshake completes. Use this to record
   * the socket in your in-memory map, send a hello frame, etc.
   * Throwing here closes the conn with 1011 (Internal Error); on_close
   * does NOT fire (we never reached steady state). */
  open?: (socket: WsSocket, ctx: { req: BrustRequest; subprotocol: string | null }) => void | Promise<void>
  /** Called per incoming message frame. data is string for Text frames,
   * Uint8Array for Binary. Throwing here is logged but the conn stays
   * open — one bad message shouldn't kill the conn; wrap in try/catch
   * for strict-close semantics. */
  message?: (socket: WsSocket, data: string | Uint8Array) => void | Promise<void>
  /** Called exactly ONCE when the conn closes EXCEPT when the author
   * called socket.close themselves. Code/reason from the RFC 6455
   * close frame; 1006 for abnormal (RST), 1011 for pong timeout,
   * 1001 for server shutdown. */
  close?: (socket: WsSocket, code: number, reason: string) => void
}

/** The only handle the author touches inside a WsHandlers callback. */
export interface WsSocket {
  /** Send a frame. Text if data is string, Binary if Uint8Array. Returns
   * a Promise that resolves when the TCP write completes (cooperative
   * backpressure, same model as SSE napi.write). Rejects with a clear
   * error if the conn is already closed. */
  send(data: string | Uint8Array): Promise<void>
  /** Initiate close with optional code (default 1000) and reason (default
   * ''). Idempotent — second call is a no-op. on_close does NOT fire
   * after this call. */
  close(code?: number, reason?: string): void
  /** Stable per-conn identifier. Useful as a Map key in author's
   * in-memory connection registry. */
  readonly id: bigint
}

export interface RouteContext<Params = Record<string, string>, Data = unknown> {
  params: Params
  path: string
  /** Value returned by `route.loader`. Undefined if the route has no loader. */
  data: Data
  /** Bun Worker id rendering this request. null before the first registerRenderer
   * return resolves (a brief window during boot). */
  workerId: number | null
  /** Structured request shape. Available to components for read-only inspection. */
  req: BrustRequest
}

export interface ErrorBoundaryProps {
  error: Error
}

export interface RouteCacheConfig {
  /** Time-to-live in seconds. */
  ttl_seconds: number
  /** Request headers that affect content. Each becomes part of the cache key. */
  vary?: string[]
}

/** Shape returned by a middleware or by the terminal `next()` (loader + render).
 * Middleware can short-circuit by returning a RouteResponse without calling next,
 * or call next() and mutate the returned response (status, headers). */
export interface RouteResponse {
  status: number
  body: string
  /** Extra response headers. Names are case-insensitive on the wire; Rust
   * deduplicates by lower-casing internally. Skips collisions with the fixed
   * Content-Type / Content-Length / Connection lines. */
  headers?: Record<string, string>
  /** Override the Content-Type emitted by Rust. Action returns set this to
   * 'application/json; charset=utf-8'; middleware short-circuits with a
   * raw string body can set 'text/plain'. Falls back to 'text/html' (render)
   * or 'application/json' (action) when omitted. */
  contentType?: string
}

/** Middleware contract — Express/Koa-style chain. Receives a structured
 * request and a `next()` that runs the rest of the chain (eventually the
 * loader + render). Return a `RouteResponse` to short-circuit, or call
 * `await next()` and return its (possibly mutated) result. */
export type Middleware = (
  req: BrustRequest,
  next: () => Promise<RouteResponse>,
) => Promise<RouteResponse>

export interface Route<Params = Record<string, string>, Data = unknown> {
  /** Relative path segment (matchit syntax). Empty string `''` = layout-only
   * (this node contributes nothing to the path; children attach to ancestors).
   * Mutually exclusive with `index: true`. */
  path?: string
  /** Index route — matches the parent path exactly. Must be a leaf (no
   * `children`, no `path`). Mutually exclusive with `path`. */
  index?: boolean
  /** TypeScript can't infer per-entry generics inside a `defineRoutes([...])`
   * literal, so the array would force every Component to accept the default
   * `RouteContext<Record<string, string>, unknown>` shape — components that
   * narrow `Params` / `Data` would fail to type-check. Keep the field
   * permissive here; each component self-declares its expected props. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Component?: ComponentType<any>
  /** Optional async function that runs in the worker before rendering. Its
   * return value becomes the component's `data` prop. Exceptions are caught
   * by `errorBoundary` if declared (inherited from closest ancestor). */
  loader?: (ctx: { params: Params; path: string; req: BrustRequest }) => Promise<Data>
  /** Optional component invoked when Component or loader throws. Inherited
   * by descendants when they don't define their own. */
  errorBoundary?: ComponentType<ErrorBoundaryProps>
  /** Opt-in cache. Cache config from the leaf only — parent's cache is
   * ignored when the route is reached as part of a chain. */
  cache?: RouteCacheConfig
  /** Per-route middleware chain. Runs in declaration order; concatenated
   * with parent middlewares (parent runs before child). Cache lookup
   * still happens BEFORE any middleware (existing rule). */
  middleware?: Middleware[]
  /** Nested children. Each child's path is composed with this node's path
   * via `joinPath` (see flattenRoutes). */
  children?: Route[]
  /** When set, this route streams a text/event-stream response. Cannot
   * coexist with Component, loader, or children (validated at defineRoutes
   * time). The framework auto-sends Content-Type, Cache-Control,
   * X-Accel-Buffering, plus a `: ping\n\n` heartbeat every 15s (opt-out
   * via sseOptions). The author returns ReadableStream<Uint8Array | string>;
   * string chunks are UTF-8 encoded. Listen on req.signal for disconnect. */
  sse?: (req: BrustRequest) => ReadableStream<Uint8Array | string> | Promise<ReadableStream<Uint8Array | string>>
  sseOptions?: {
    /** Auto-emit `: ping\n\n` every N ms. Default 15000. Set 0 to disable. */
    heartbeatMs?: number
  }
  /** When set, this route accepts WebSocket upgrades. Cannot coexist
   * with Component, loader, sse, or children (validated at defineRoutes
   * time). The factory is invoked lazily by the WS dispatch path and
   * cached per worker. The handler module may export `WsHandlers`
   * directly OR as a `default` (the common `() => import('./ws-foo')`
   * pattern returns a module namespace `{ default: WsHandlers }`);
   * `handleWsConn` unwraps `.default` defensively at call time. */
  websocket?: () => Promise<WsHandlers | { default: WsHandlers }>
  wsOptions?: {
    /** Server-initiated ping interval in ms. Default 30000. Set 0 to disable.
     * Pong timeout = 2× pingMs; conn closes with code 1011 if no pong by then. */
    pingMs?: number
    /** Max message size in bytes. Default 1 048 576 (1 MB). Larger frames
     * close the conn with 1009 (Message Too Big). */
    maxMessageBytes?: number
    /** Subprotocols the route supports (Sec-WebSocket-Protocol). Client's
     * requested list is intersected with this; first match (in this declared
     * order) wins and is reflected in Sec-WebSocket-Protocol response. */
    subprotocols?: string[]
  }
}

/** Internal post-flatten representation. Each FlatRoute is a single leaf or
 * index route in the user's nested tree. Indexed by Rust's route_id (array
 * position). Consumed by `makeRenderer` and structurally compatible with
 * `brust.registerRoutes` (reads only `fullPath` and `cache`). */
export interface FlatRoute {
  /** Full path Rust matches against. Composed from the chain via joinPath. */
  fullPath: string
  /** Chain of Route nodes from root to leaf, inclusive. Renderer walks
   * this top-down. */
  chain: Route[]
  /** Concatenated middleware from root → leaf. composeChain wraps right-to-left,
   * so the first element here becomes the outermost wrap (runs first). */
  middleware: Middleware[]
  /** Closest errorBoundary in the chain (leaf wins; falls back up the chain). */
  errorBoundary?: ComponentType<ErrorBoundaryProps>
  /** Cache from the leaf only — no parent inheritance. */
  cache?: RouteCacheConfig
}

/** Compose a child's relative path onto a parent's base path.
 *  - `rel === ''` (layout-only child) → returns `base` unchanged
 *  - `rel` starts with `/` (absolute) → returns `rel` (only valid when base === '';
 *    flattenRoutes rejects this case otherwise)
 *  - otherwise → strip any trailing `/` from base, append `/${rel}` */
export function joinPath(base: string, rel: string): string {
  if (rel === '') return base
  if (rel.startsWith('/')) return rel
  const trimmedBase = base.endsWith('/') ? base.slice(0, -1) : base
  return `${trimmedBase}/${rel}`
}

/** Validate a Route node's structural invariants in the context of its
 * parent's basePath. Throws with a useful message at module top-level —
 * route bugs fail loudly before brust.serve binds. */
function validateRoute(r: Route, basePath: string): void {
  if (r.index === true && r.path !== undefined) {
    throw new Error(`route under "${basePath}": cannot set both index and path`)
  }
  if (r.index === true && r.children && r.children.length > 0) {
    throw new Error(`route under "${basePath}": index route cannot have children`)
  }
  if (!r.index && r.path === undefined && !(r.children && r.children.length > 0)) {
    throw new Error(`route under "${basePath}": must have path, index, or children`)
  }
  if (r.path !== undefined && r.path.startsWith('/') && basePath !== '') {
    // Absolute children under a non-empty parent are a footgun (the child
    // escapes the parent's URL space). Only allowed when the parent is
    // layout-only (basePath === '').
    throw new Error(
      `route under "${basePath}": absolute child path "${r.path}" must be under a pathless ('') parent`,
    )
  }
  if (r.sse) {
    const where = r.path ?? '(no path)'
    if (r.Component !== undefined) {
      throw new Error(`Route ${where}: 'sse' cannot coexist with 'Component'`)
    }
    if (r.loader !== undefined) {
      throw new Error(`Route ${where}: 'sse' cannot coexist with 'loader'`)
    }
    if (r.children !== undefined) {
      throw new Error(`Route ${where}: 'sse' cannot have nested children`)
    }
  }
  if (r.websocket) {
    const where = r.path ?? '(no path)'
    if (r.Component !== undefined) {
      throw new Error(`Route ${where}: 'websocket' cannot coexist with 'Component'`)
    }
    if (r.loader !== undefined) {
      throw new Error(`Route ${where}: 'websocket' cannot coexist with 'loader'`)
    }
    if (r.sse !== undefined) {
      throw new Error(`Route ${where}: 'websocket' cannot coexist with 'sse'`)
    }
    if (r.children !== undefined) {
      throw new Error(`Route ${where}: 'websocket' cannot have nested children`)
    }
  }
}

/** Walk the nested route tree, emitting one FlatRoute per leaf or index node.
 * Composes paths, middleware, errorBoundary, and cache per the rules in
 * the design spec (§3). */
export function flattenRoutes(routes: Route[]): FlatRoute[] {
  const out: FlatRoute[] = []
  walkRoutes(routes, [], '', out)
  return out
}

function walkRoutes(
  routes: Route[],
  parentChain: Route[],
  basePath: string,
  out: FlatRoute[],
): void {
  for (const r of routes) {
    validateRoute(r, basePath)
    const chain = [...parentChain, r]

    if (r.index === true) {
      out.push(makeFlat(chain, basePath))
      continue
    }

    const ownPath = r.path ?? ''
    const myPath = joinPath(basePath, ownPath)

    if (r.children && r.children.length > 0) {
      walkRoutes(r.children, chain, myPath, out)
    } else {
      // Leaf with a path (validated above).
      out.push(makeFlat(chain, myPath))
    }
  }
}

function makeFlat(chain: Route[], fullPath: string): FlatRoute {
  const middleware: Middleware[] = []
  for (const r of chain) {
    if (r.middleware) middleware.push(...r.middleware)
  }
  let errorBoundary: ComponentType<ErrorBoundaryProps> | undefined
  for (const r of chain) {
    if (r.errorBoundary) errorBoundary = r.errorBoundary
  }
  const cache = chain[chain.length - 1].cache
  return { fullPath, chain, middleware, errorBoundary, cache }
}

/** Internal React context that carries the next-deeper rendered element to
 * the parent's <Outlet />. Default `null` means "no child to render" —
 * `<Outlet />` from a leaf route or a flat route renders nothing. */
export const OutletContext = createContext<ReactNode>(null)

/** Renders the matched child route inside a parent layout. Read via
 * React context; falls back to null at the leaf or in a flat (non-nested)
 * route. Use inside a parent Component:
 *
 *     function AdminLayout() {
 *       return <div><nav>…</nav><main><Outlet /></main></div>
 *     }
 */
export function Outlet(): ReactNode {
  return useContext(OutletContext)
}

/** Process the user's nested route tree into a flat array for the renderer
 * and Rust route table. Each leaf/index node becomes one FlatRoute. Indices
 * are stable across worker reloads (= array position), matching Rust's
 * route_id semantics. */
export function defineRoutes(routes: Route[]): FlatRoute[] {
  return flattenRoutes(routes)
}

/** Wire-level shape of the JSON envelope produced by Rust. Discriminated
 * union: render path (matched against a route) vs action path
 * (POST /_brust/action/<id>). Keep these in sync with src/routes.rs
 * RouteEnvelope / ActionEnvelope.
 */
export type RouteCall =
  | {
      kind: 'render'
      route_id: number
      path: string
      params: Record<string, string>
      req: BrustRequest
    }
  | {
      kind: 'action'
      action_id: string
      /** Request's Content-Type, whitespace-trimmed (case preserved by Rust;
       * the dispatch points below lowercase defensively). '' means the header
       * was missing. */
      content_type: string
      /** UTF-8 text body — present for application/json and
       * application/x-www-form-urlencoded. Mutually exclusive with body_b64. */
      body_text?: string
      /** Base64-encoded binary body — present for multipart/form-data.
       * JS decodes via Buffer.from(s, 'base64') before parsing. */
      body_b64?: string
      req: BrustRequest
    }
  | {
      kind: 'mcp'
      body_text: string
      req: BrustRequest
    }
  | {
      kind: 'sse'
      conn_id: bigint
      req: BrustRequest
    }
  | {
      kind: 'ws'
      conn_id: bigint
      client_subprotocols: string[]
      req: BrustRequest
    }

/**
 * Build a render callback for a given routes table. The returned function is
 * what gets passed to `brust.registerRenderer(view, fn)` on the worker side.
 *
 * Wire format written to the SAB: [meta_len: u16 BE][meta JSON UTF-8][body bytes].
 * meta = { status: number, headers?: Record<string, string> }.
 */
export interface MakeRendererOptions {
  /** Lazy getter for the Bun Worker id. Called per-render so the value can be
   * resolved after `registerRenderer` returns. Returns null before that. */
  getWorkerId?: () => number | null
  /** Action table the worker dispatches to when envelope.kind === 'action'.
   * Both the main process and each worker call `brust.scanActions(...)` at
   * module top-level and pass the resulting array here — the wire keys (ids)
   * and the handler functions (fn) must agree across both ends. */
  actions?: ActionDef[]
  /** MCP server instance — built once per worker at module top-level. */
  mcp?: import('./mcp/server.ts').McpServer
}

export function makeRenderer(
  routes: FlatRoute[],
  view: Uint8Array,
  opts: MakeRendererOptions = {},
): (envelopeJson: string) => Promise<void> {
  const encoder = new TextEncoder()
  const byRouteId = new Map<number, FlatRoute>()
  routes.forEach((r, i) => byRouteId.set(i, r))
  const byActionId = new Map<string, ActionDef>()
  for (const a of opts.actions ?? []) byActionId.set(a.id, a)

  // napi shim for the chunk channel. The sabBytes arg is ignored by the
  // native fn (Rust reads from the pre-registered BufPtr) — the call sites
  // still pass it so renderBranchStreaming can be unit-tested against a
  // mock that captures the bytes.
  const napi = {
    renderChunk: async (workerId: bigint, len: number, _sabBytes: Uint8Array): Promise<void> => {
      await (native as any).napiRenderChunk(Number(workerId), len)
    },
  }

  return async (envelopeJson: string): Promise<void> => {
    const call = JSON.parse(envelopeJson) as RouteCall
    const wid = opts.getWorkerId?.() ?? 0
    const workerId = BigInt(wid)

    if (call.kind === 'render') {
      const flat = byRouteId.get(call.route_id)
      if (!flat) {
        console.error(`[brust] unknown route_id=${call.route_id} for path=${call.path}`)
        await emitSingleChunkResponse(view, napi, workerId, encoder, {
          status: 404, contentType: 'text/plain; charset=utf-8', body: 'not found',
        })
        return
      }
      // Inject the permanently-unaborted signal — non-SSE routes don't
      // have a per-conn AbortController. Middleware/loaders/components
      // can still read req.signal.aborted (always false).
      call.req.signal = NEVER_ABORTS

      // Run the middleware chain against a streaming-marker terminal.
      // Middleware that short-circuits (returns without calling next())
      // wins as a plain single-chunk response. Middleware that calls next()
      // gets the marker back and can wrap/mutate `headers` and `status`
      // before we hand control to renderBranchStreaming.
      const STREAM_MARKER: unique symbol = Symbol.for('brust.streamRender')
      type StreamMarkerResponse = RouteResponse & { _brustStream?: typeof STREAM_MARKER }
      const streamTerminal: () => Promise<StreamMarkerResponse> = async () => ({
        status: 200,
        body: '',
        contentType: 'text/html; charset=utf-8',
        _brustStream: STREAM_MARKER,
      })
      const chain = composeChain(call.req, flat.middleware, streamTerminal)

      let verdict: StreamMarkerResponse
      try {
        verdict = await chain() as StreamMarkerResponse
      } catch (err) {
        console.error(`[brust] middleware/render uncaught:`, err)
        await emitSingleChunkResponse(view, napi, workerId, encoder, {
          status: 500, contentType: 'text/html; charset=utf-8', body: 'internal error',
        })
        return
      }

      if (verdict._brustStream !== STREAM_MARKER) {
        // Middleware short-circuited with a concrete response.
        await emitSingleChunkResponse(view, napi, workerId, encoder, {
          status: verdict.status,
          contentType: verdict.contentType ?? 'text/html; charset=utf-8',
          body: verdict.body,
          headers: verdict.headers,
        })
        return
      }

      let element: ReactNode
      let errorBoundary: ComponentType<{ error: Error }>
      try {
        element = await buildRenderElement(call, flat, opts.getWorkerId)
        errorBoundary = flat.errorBoundary ??
          (({ error }) => createElement('div', null, `Internal Server Error: ${error.message}`))
      } catch (err) {
        // Setup failure BEFORE renderToPipeableStream — loader throw, params
        // bind throw. Shape matches the legacy "internal error" path so
        // existing integration tests stay green.
        console.error(`[brust] render setup failed:`, err)
        await emitSingleChunkResponse(view, napi, workerId, encoder, {
          status: 500, contentType: 'text/html; charset=utf-8', body: 'internal error',
        })
        return
      }
      await renderBranchStreaming({
        element, view, workerId, napi, errorBoundary,
        status: verdict.status,
        headers: verdict.headers,
      })
      return
    }
    if (call.kind === 'action') {
      const resp = await actionBranchToResponse(call, byActionId)
      await emitSingleChunkResponse(view, napi, workerId, encoder, resp)
      return
    }
    if (call.kind === 'mcp') {
      const resp = await mcpBranchToResponse(call, opts.mcp)
      await emitSingleChunkResponse(view, napi, workerId, encoder, resp)
      return
    }
    if (call.kind === 'sse') {
      try {
        await sseBranch(call, view, encoder, routes)
      } catch (err) {
        // Setup-time errors only (BigInt coerce, dynamic import resolve,
        // napi shim build). Once handleSseStream has started streaming,
        // Rust already wrote 200 headers and frames — this 500 is irrelevant.
        console.error('[brust] sseBranch uncaught:', err)
      }
      // SSE bypasses the chunk channel entirely — handleSseStream owns the
      // socket via napiSse* fns. No renderChunk calls here.
      return
    }
    if (call.kind === 'ws') {
      try {
        await wsBranch(call, view, encoder, routes)
      } catch (err) {
        // Setup-time errors only — same reasoning as sseBranch above.
        console.error('[brust] wsBranch uncaught:', err)
      }
      // WS bypasses the chunk channel entirely — handleWsConn owns the
      // socket via napiWs* fns. No renderChunk calls here.
      return
    }
    // Unknown kind — log and 500. Shouldn't happen unless Rust ships
    // something out of band.
    console.error(`[brust] unknown envelope kind in worker:`, (call as { kind?: string }).kind)
    await emitSingleChunkResponse(view, napi, workerId, encoder, {
      status: 500, contentType: 'text/plain; charset=utf-8', body: 'invalid envelope kind',
    })
  }
}

/** Build the React element for a render call: runs loaders top-down, builds
 * the element bottom-up wrapping in OutletContext.Provider so nested routes
 * receive the deeper element via <Outlet />. Also runs the middleware chain;
 * the terminal returns a synthesised "render-only" element wrapped in any
 * short-circuit/redirect markers via the middleware-applied transform.
 *
 * Throws on setup failure (loader throw, middleware throw, etc.). The caller
 * synthesises a 500 in that case — renderBranchStreaming is reserved for
 * actual element-tree rendering where Suspense + errorBoundary apply.
 */
async function buildRenderElement(
  call: Extract<RouteCall, { kind: 'render' }>,
  flat: FlatRoute,
  getWorkerId?: () => number | null,
): Promise<ReactNode> {
  call.req.signal = NEVER_ABORTS
  const workerId = getWorkerId ? getWorkerId() : null
  const chainNodes = flat.chain

  // 1. Run loaders top-down (parent → leaf). Each Component receives ONLY
  //    its own loader's data — no merge, no inheritance.
  const datas: unknown[] = new Array(chainNodes.length)
  for (let i = 0; i < chainNodes.length; i++) {
    const r = chainNodes[i]
    datas[i] = r.loader
      ? await r.loader({ params: call.params, path: call.path, req: call.req })
      : undefined
  }

  // 2. Build the React element bottom-up. Each level wraps the deeper level
  //    via <OutletContext.Provider value={renderedChild}>; <Outlet /> in any
  //    parent Component returns that value.
  let element: ReactNode = null
  for (let i = chainNodes.length - 1; i >= 0; i--) {
    const r = chainNodes[i]
    const node = createElement(r.Component!, {
      params: call.params,
      path: call.path,
      data: datas[i],
      workerId,
      req: call.req,
    })
    element = createElement(OutletContext.Provider, { value: element }, node)
  }
  return element
}

/** Emit a single-chunk response through the chunk channel — wire shape
 * matches what dispatch_to_worker_and_stream_chunks expects (one Bytes
 * chunk with `[meta_len][meta][body]`, then Final). Used by action/mcp
 * branches and by setup-failure fallbacks in the render branch. */
async function emitSingleChunkResponse(
  view: Uint8Array,
  napi: { renderChunk: (w: bigint, len: number, view: Uint8Array) => Promise<void> },
  workerId: bigint,
  encoder: TextEncoder,
  resp: { status: number; contentType: string; body: string | Uint8Array; headers?: Record<string, string> },
): Promise<void> {
  const bodyBytes = typeof resp.body === 'string' ? encoder.encode(resp.body) : resp.body
  const meta = JSON.stringify({
    status: resp.status,
    contentType: resp.contentType,
    headers: resp.headers ?? {},
    streaming: false,
  })
  const metaBytes = encoder.encode(meta)
  const total = 2 + metaBytes.length + bodyBytes.length
  if (total > view.length) {
    console.error(`[brust] single-chunk response ${total}b exceeds SAB ${view.length}b — emitting 500`)
    // Emit a proper 500 plain-text response so the client doesn't hang on
    // TCP timeout waiting for a body that never comes. The fallback body is
    // small enough to always fit in the SAB.
    const errBody = encoder.encode('response body too large')
    const errMeta = JSON.stringify({
      status: 500,
      contentType: 'text/plain; charset=utf-8',
      headers: {},
      streaming: false,
    })
    const errMetaBytes = encoder.encode(errMeta)
    const errTotal = 2 + errMetaBytes.length + errBody.length
    view[0] = (errMetaBytes.length >> 8) & 0xff
    view[1] = errMetaBytes.length & 0xff
    view.set(errMetaBytes, 2)
    view.set(errBody, 2 + errMetaBytes.length)
    await napi.renderChunk(workerId, errTotal, view)
    await napi.renderChunk(workerId, 0, view)
    return
  }
  view[0] = (metaBytes.length >> 8) & 0xff
  view[1] = metaBytes.length & 0xff
  view.set(metaBytes, 2)
  view.set(bodyBytes, 2 + metaBytes.length)
  await napi.renderChunk(workerId, total, view)
  await napi.renderChunk(workerId, 0, view)
}

/** Plain response object shape returned by action/mcp branches and consumed
 * by `emitSingleChunkResponse`. The branches no longer write to the SAB
 * directly — they hand back a JS-side response and the caller packs +
 * dispatches it through the chunk channel. */
interface BranchResponse {
  status: number
  contentType: string
  body: string | Uint8Array
  headers?: Record<string, string>
}

async function actionBranchToResponse(
  call: Extract<RouteCall, { kind: 'action' }>,
  byId: Map<string, ActionDef>,
): Promise<BranchResponse> {
  const def = byId.get(call.action_id)
  if (!def) {
    // Rust already 404s when the id isn't registered, but a race during
    // hot-reload (or a desynced worker) could land here. Log and 404.
    // Action clients always expect JSON, so ship a JSON envelope even
    // when Rust would have 404'd first.
    console.error(`[brust] unknown action_id=${call.action_id}`)
    return {
      status: 404,
      body: '{"error":{"message":"unknown action"}}',
      contentType: 'application/json; charset=utf-8',
    }
  }
  // Populate req.signal with the permanently-unaborted sentinel. Action
  // handlers reading req.signal.aborted always see false; the SSE branch
  // is where real disconnect lives.
  call.req.signal = NEVER_ABORTS

  // Decode the body into the args array that will be spread into the handler.
  // Three paths: multipart (body_b64), form-urlencoded (body_text), or JSON (body_text).
  // Body decode happens BEFORE middleware so a malformed body 400s without running
  // any user code.
  let args: unknown[]
  try {
    if (call.body_b64 !== undefined) {
      // Multipart path — base64 → bytes → Web Request.formData()
      const bytes = Buffer.from(call.body_b64, 'base64')
      const synthReq = new Request('http://x', {
        method: 'POST',
        headers: { 'Content-Type': call.content_type },
        body: bytes,
      })
      const fd = await synthReq.formData()
      args = [fd]
    } else if (call.content_type.toLowerCase().startsWith('application/x-www-form-urlencoded')) {
      // Form-urlencoded path — URLSearchParams → FormData
      const params = new URLSearchParams(call.body_text ?? '')
      const fd = new FormData()
      for (const [k, v] of params) fd.append(k, v)
      args = [fd]
    } else {
      // JSON path (default — empty or application/json content type).
      const decoded = JSON.parse(call.body_text ?? '') as unknown
      if (!Array.isArray(decoded)) {
        return {
          status: 400,
          body: '{"error":{"message":"args must be a JSON array"}}',
          contentType: 'application/json; charset=utf-8',
        }
      }
      args = decoded
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return {
      status: 400,
      body: JSON.stringify({ error: { message: `invalid request body: ${msg}` } }),
      contentType: 'application/json; charset=utf-8',
    }
  }

  const terminal = async (): Promise<RouteResponse> => {
    try {
      const result = await def.fn(call.req, ...args)
      return {
        status: 200,
        body: result === undefined ? '' : JSON.stringify(result),
        contentType: 'application/json; charset=utf-8',
      }
    } catch (err) {
      console.error(`[brust] action ${def.id} threw:`, err)
      const e = err instanceof Error ? err : new Error(String(err))
      return {
        status: 500,
        body: JSON.stringify({ error: { message: e.message, name: e.name } }),
        contentType: 'application/json; charset=utf-8',
      }
    }
  }

  const chain = composeChain(call.req, def.middleware, terminal)

  let response: RouteResponse
  try {
    response = await chain()
  } catch (err) {
    console.error(`[brust] action middleware uncaught:`, err)
    response = {
      status: 500,
      body: JSON.stringify({ error: { message: 'internal error' } }),
      contentType: 'application/json; charset=utf-8',
    }
  }
  return {
    status: response.status,
    body: response.body,
    contentType: response.contentType ?? 'application/json; charset=utf-8',
    headers: response.headers,
  }
}

async function mcpBranchToResponse(
  call: Extract<RouteCall, { kind: 'mcp' }>,
  mcp: import('./mcp/server.ts').McpServer | undefined,
): Promise<BranchResponse> {
  if (!mcp) {
    return {
      status: 501,
      body: '{"jsonrpc":"2.0","id":null,"error":{"code":-32603,"message":"mcp not configured"}}',
      contentType: 'application/json; charset=utf-8',
    }
  }
  // Populate req.signal with the permanently-unaborted sentinel. MCP handler
  // reading req.signal.aborted always sees false; the SSE branch is where
  // real disconnect lives.
  call.req.signal = NEVER_ABORTS
  const responseJson = await mcp.handleRequest(call.body_text, call.req)
  if (responseJson === '') {
    // Notification — no response body. Return 204 No Content.
    return {
      status: 204,
      body: '',
      contentType: 'application/json; charset=utf-8',
    }
  }
  return {
    status: 200,
    body: responseJson,
    contentType: 'application/json; charset=utf-8',
  }
}

async function sseBranch(
  call: Extract<RouteCall, { kind: 'sse' }>,
  _view: Uint8Array,
  encoder: TextEncoder,
  routes: FlatRoute[],
): Promise<void> {
  // conn_id crosses the boundary as a JSON number (u64) but napiSse* fns
  // require BigInt. Coerce once here; reassign on the call object so
  // handleSseStream (which reads call.conn_id directly) also gets bigint.
  ;(call as any).conn_id = BigInt((call as any).conn_id)

  // Find matching FlatRoute by literal path (MVP — exact match; Rust's
  // path_is_sse gates dispatch so we only see registered paths). Strip
  // query string before matching.
  // Rust's path_is_sse uses the same literal-match registration as this
  // find — trailing-slash divergence (or any other normalization) fails
  // in lockstep on both sides, never producing silent half-state.
  const pathOnly = call.req.url.split('?')[0]
  const flat = routes.find((r) => r.fullPath === pathOnly)
  const leaf = flat?.chain[flat.chain.length - 1]

  // Build napi shim around the four napiSse* native fns. signalOpen
  // wraps the body string in a Buffer (the Rust side takes Buffer).
  // Dynamic import is consistent with mcpBranch/actionBranch — defers
  // loading the native binding until the dispatch path actually fires
  // and avoids any circular-import risk during module init.
  const native = await import('./index.js')
  const napi = {
    write: (conn_id: bigint, bytes: Uint8Array) =>
      (native as any).napiSseWrite(conn_id, Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength)),
    close: (conn_id: bigint) =>
      (native as any).napiSseClose(conn_id),
    registerAbort: (conn_id: bigint, cb: () => void) =>
      (native as any).napiSseRegisterAbort(conn_id, cb),
    signalOpen: (conn_id: bigint, status: number, body: string, ct: string) => {
      const bodyBytes = encoder.encode(body)
      ;(native as any).napiSseSignalOpen(
        conn_id, status,
        Buffer.from(bodyBytes.buffer, bodyBytes.byteOffset, bodyBytes.byteLength),
        ct,
      )
    },
  }

  if (!flat || !leaf || !leaf.sse) {
    // Defensive — shouldn't reach here since Rust gates by path_is_sse.
    napi.signalOpen(call.conn_id, 404, 'not found', 'text/plain; charset=utf-8')
    napi.close(call.conn_id)
    return
  }

  // Inject NEVER_ABORTS into req for the middleware run. handleSseStream
  // will overwrite with a per-conn AbortController.signal afterward.
  call.req.signal = NEVER_ABORTS

  // Run middleware chain with a 200 placeholder terminal. The terminal
  // does NOT invoke leaf.sse — handleSseStream does that after middleware
  // approves. This keeps middleware semantics identical to action/render.
  const placeholderTerminal: () => Promise<RouteResponse> = async () => ({
    status: 200, body: '', contentType: 'text/event-stream',
  })
  const chain = composeChain(call.req, flat.middleware, placeholderTerminal)
  const verdict = await chain()

  if (verdict.status >= 400) {
    napi.signalOpen(
      call.conn_id, verdict.status, verdict.body,
      verdict.contentType ?? 'text/plain; charset=utf-8',
    )
    napi.close(call.conn_id)
    return
  }

  // Middleware OK — invoke handleSseStream which signals open 200 itself
  // and runs the reader loop until done or aborted.
  const { handleSseStream } = await import('./sse/handler.ts')
  const routeShim: Route = {
    path: flat.fullPath,
    sse: leaf.sse,
    sseOptions: leaf.sseOptions,
  }
  await handleSseStream(call, routeShim, napi)
}

async function wsBranch(
  call: Extract<RouteCall, { kind: 'ws' }>,
  _view: Uint8Array,
  encoder: TextEncoder,
  routes: FlatRoute[],
): Promise<void> {
  // Coerce conn_id from JSON.parse number → BigInt (same fix as sseBranch
  // Task 12; native binding requires BigInt since conn_ids are u64).
  ;(call as any).conn_id = BigInt(call.conn_id)

  // Find matching FlatRoute by literal fullPath (Rust path_is_ws gates
  // dispatch — same literal-match contract as SSE).
  const pathOnly = call.req.url.split('?')[0]
  const flat = routes.find((r) => r.fullPath === pathOnly)
  const leaf = flat?.chain[flat.chain.length - 1]

  // Build napi shim around the 4 napiWs* native fns. The registerHandlers
  // shim adapts from struct-arg callbacks (WsMessageArg / WsCloseArg —
  // Task 4 deviation: napi-rs rejected tuple Function args) to the
  // positional-arg handleWsConn API.
  const native = await import('./index.js')
  const napi = {
    send: (conn_id: bigint, bytes: Uint8Array, isBinary: boolean) =>
      (native as any).napiWsSend(
        conn_id,
        Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength),
        isBinary,
      ),
    close: (conn_id: bigint, code: number, reason: string) =>
      (native as any).napiWsClose(conn_id, code, reason),
    signalOpen: (conn_id: bigint, status: number, body: string, ct: string, subprotocol: string) => {
      const bodyBytes = encoder.encode(body)
      ;(native as any).napiWsSignalOpen(
        conn_id, status,
        Buffer.from(bodyBytes.buffer, bodyBytes.byteOffset, bodyBytes.byteLength),
        ct, subprotocol,
      )
    },
    registerHandlers: (
      conn_id: bigint,
      onMessage: (data: Uint8Array, isBinary: boolean) => void,
      onClose: (code: number, reason: string) => void,
    ) => {
      // napi-rs delivers struct args (WsMessageArg / WsCloseArg) — adapt
      // back to positional for handleWsConn's contract.
      ;(native as any).napiWsRegisterHandlers(
        conn_id,
        (arg: { data: Uint8Array; isBinary: boolean }) => onMessage(arg.data, arg.isBinary),
        (arg: { code: number; reason: string }) => onClose(arg.code, arg.reason),
      )
    },
  }

  if (!flat || !leaf || !leaf.websocket) {
    // Defensive — Rust path_is_ws gates dispatch.
    napi.signalOpen(call.conn_id, 404, 'not found', 'text/plain; charset=utf-8', '')
    return
  }

  // Inject NEVER_ABORTS into req for middleware. There's no per-conn
  // AbortController for WS — handleWsConn doesn't create one because
  // lifecycle is via registered onMessage/onClose callbacks rather than
  // awaiting on a request signal.
  call.req.signal = NEVER_ABORTS

  // Run middleware chain with a 101 placeholder terminal that signals
  // "ready to upgrade". The terminal does NOT call route.websocket —
  // handleWsConn does that after middleware approves.
  const placeholderTerminal: () => Promise<RouteResponse> = async () => ({
    status: 101, body: '', contentType: 'application/octet-stream',
  })
  const chain = composeChain(call.req, flat.middleware, placeholderTerminal)
  const verdict = await chain()

  if (verdict.status >= 400) {
    napi.signalOpen(
      call.conn_id, verdict.status, verdict.body,
      verdict.contentType ?? 'text/plain; charset=utf-8',
      '',
    )
    return
  }

  // Middleware OK — invoke handleWsConn. It signals open 101 itself
  // (with the chosen subprotocol) and registers handlers.
  const { handleWsConn } = await import('./ws/handler.ts')
  const routeShim: Route = {
    path: flat.fullPath,
    websocket: leaf.websocket,
    wsOptions: leaf.wsOptions,
  }
  await handleWsConn(call, routeShim, napi)
}

/** Right-to-left compose a middleware chain. Each middleware wraps the next;
 * the terminal step ends up at the innermost call. Returning without calling
 * next() short-circuits. Used identically by render + action branches. */
export function composeChain(
  req: BrustRequest,
  mws: Middleware[] | undefined,
  terminal: () => Promise<RouteResponse>,
): () => Promise<RouteResponse> {
  if (!mws || mws.length === 0) return terminal
  let chain = terminal
  for (let i = mws.length - 1; i >= 0; i--) {
    const mw = mws[i]
    const next = chain
    chain = () => mw(req, next)
  }
  return chain
}

