// generated by brust v2 — client chunk for input_517275ac
import { signal, computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_517275ac", ({ el, props, effect, onCleanup, ref }) => {
  const count = signal(0)
  const _h1 = (...a) => (() => count.set(count() + 1))(...a)
  const _p1 = computed(() => ({ n: count(), onReset: () => count.set(0) }))
  return { count, _h1, _p1 }
})
