// generated by brust v2 — client chunk for counter_1f1ff519
import { computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("counter_1f1ff519", ({ el, props, effect, onCleanup, ref }) => {
  const _h1 = (...a) => ((...a) => (props().onReset)(...a))(...a)
  const _c1 = computed(() => props().n)
  return { _h1, _c1 }
})
