// generated by brust v2 — client chunk for input_c1c07ee9
import { computed, defineBehavior } from "brust/runtime-dom"
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("input_c1c07ee9", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _c1 = computed(() => __text(props().summary))
  const _l1 = computed(() => props().rows)
  const _k1 = (p) => p.id
  const _c2 = (p) => __text(p.num)
  const _c3 = (p) => __text(p.displayName)
  const _l2 = (p) => p.badges
  const _k2 = (b) => b.type
  const _p1 = (p, b) => ({ type: b.type, label: b.label, color: b.color })
  return { _c1, _l1, _k1, _c2, _c3, _l2, _k2, _p1 }
})
