//! React-compatible JSX prop to serialized DOM attribute names.
//!
//! The SVG entries are derived from the canonical prop surface and serializer
//! behavior in the pinned ReactDOM 19.2.6 bundle. Lowercase attributes remain
//! passthrough and therefore do not need entries here.

static STANDARD_ATTRS: &[(&str, &str)] = &[
    ("accentHeight", "accent-height"),
    ("alignmentBaseline", "alignment-baseline"),
    ("allowReorder", "allowReorder"),
    ("arabicForm", "arabic-form"),
    ("attributeName", "attributeName"),
    ("attributeType", "attributeType"),
    ("autoReverse", "autoReverse"),
    ("baseFrequency", "baseFrequency"),
    ("baseProfile", "baseProfile"),
    ("baselineShift", "baseline-shift"),
    ("calcMode", "calcMode"),
    ("capHeight", "cap-height"),
    ("charSet", "charset"),
    ("className", "class"),
    ("clipPath", "clip-path"),
    ("clipPathUnits", "clipPathUnits"),
    ("clipRule", "clip-rule"),
    ("colSpan", "colspan"),
    ("colorInterpolation", "color-interpolation"),
    ("colorInterpolationFilters", "color-interpolation-filters"),
    ("colorProfile", "color-profile"),
    ("colorRendering", "color-rendering"),
    ("contentScriptType", "contentScriptType"),
    ("contentStyleType", "contentStyleType"),
    ("crossOrigin", "crossorigin"),
    ("diffuseConstant", "diffuseConstant"),
    ("dominantBaseline", "dominant-baseline"),
    ("edgeMode", "edgeMode"),
    ("enableBackground", "enable-background"),
    ("externalResourcesRequired", "externalResourcesRequired"),
    ("fillOpacity", "fill-opacity"),
    ("fillRule", "fill-rule"),
    ("filterRes", "filterRes"),
    ("filterUnits", "filterUnits"),
    ("floodColor", "flood-color"),
    ("floodOpacity", "flood-opacity"),
    ("fontFamily", "font-family"),
    ("fontSize", "font-size"),
    ("fontSizeAdjust", "font-size-adjust"),
    ("fontStretch", "font-stretch"),
    ("fontStyle", "font-style"),
    ("fontVariant", "font-variant"),
    ("fontWeight", "font-weight"),
    ("glyphName", "glyph-name"),
    ("glyphOrientationHorizontal", "glyph-orientation-horizontal"),
    ("glyphOrientationVertical", "glyph-orientation-vertical"),
    ("glyphRef", "glyphRef"),
    ("gradientTransform", "gradientTransform"),
    ("gradientUnits", "gradientUnits"),
    ("horizAdvX", "horiz-adv-x"),
    ("horizOriginX", "horiz-origin-x"),
    ("htmlFor", "for"),
    ("imageRendering", "image-rendering"),
    ("kernelMatrix", "kernelMatrix"),
    ("kernelUnitLength", "kernelUnitLength"),
    ("keyPoints", "keyPoints"),
    ("keySplines", "keySplines"),
    ("keyTimes", "keyTimes"),
    ("lengthAdjust", "lengthAdjust"),
    ("letterSpacing", "letter-spacing"),
    ("lightingColor", "lighting-color"),
    ("limitingConeAngle", "limitingConeAngle"),
    ("markerEnd", "marker-end"),
    ("markerHeight", "markerHeight"),
    ("markerMid", "marker-mid"),
    ("markerStart", "marker-start"),
    ("markerUnits", "markerUnits"),
    ("markerWidth", "markerWidth"),
    ("maskContentUnits", "maskContentUnits"),
    ("maskUnits", "maskUnits"),
    ("maxLength", "maxlength"),
    ("numOctaves", "numOctaves"),
    ("overlinePosition", "overline-position"),
    ("overlineThickness", "overline-thickness"),
    ("paintOrder", "paint-order"),
    ("pathLength", "pathLength"),
    ("patternContentUnits", "patternContentUnits"),
    ("patternTransform", "patternTransform"),
    ("patternUnits", "patternUnits"),
    ("pointerEvents", "pointer-events"),
    ("pointsAtX", "pointsAtX"),
    ("pointsAtY", "pointsAtY"),
    ("pointsAtZ", "pointsAtZ"),
    ("popoverTarget", "popoverTarget"),
    ("popoverTargetAction", "popoverTargetAction"),
    ("preserveAlpha", "preserveAlpha"),
    ("preserveAspectRatio", "preserveAspectRatio"),
    ("primitiveUnits", "primitiveUnits"),
    ("readOnly", "readonly"),
    ("refX", "refX"),
    ("refY", "refY"),
    ("renderingIntent", "rendering-intent"),
    ("repeatCount", "repeatCount"),
    ("repeatDur", "repeatDur"),
    ("requiredExtensions", "requiredExtensions"),
    ("requiredFeatures", "requiredFeatures"),
    ("rowSpan", "rowspan"),
    ("shapeRendering", "shape-rendering"),
    ("specularConstant", "specularConstant"),
    ("specularExponent", "specularExponent"),
    ("spreadMethod", "spreadMethod"),
    ("srcSet", "srcset"),
    ("startOffset", "startOffset"),
    ("stdDeviation", "stdDeviation"),
    ("stitchTiles", "stitchTiles"),
    ("stopColor", "stop-color"),
    ("stopOpacity", "stop-opacity"),
    ("strikethroughPosition", "strikethrough-position"),
    ("strikethroughThickness", "strikethrough-thickness"),
    ("strokeDasharray", "stroke-dasharray"),
    ("strokeDashoffset", "stroke-dashoffset"),
    ("strokeLinecap", "stroke-linecap"),
    ("strokeLinejoin", "stroke-linejoin"),
    ("strokeMiterlimit", "stroke-miterlimit"),
    ("strokeOpacity", "stroke-opacity"),
    ("strokeWidth", "stroke-width"),
    ("surfaceScale", "surfaceScale"),
    ("systemLanguage", "systemLanguage"),
    ("tabIndex", "tabindex"),
    ("tableValues", "tableValues"),
    ("targetX", "targetX"),
    ("targetY", "targetY"),
    ("textAnchor", "text-anchor"),
    ("textDecoration", "text-decoration"),
    ("textLength", "textLength"),
    ("textRendering", "text-rendering"),
    ("transformOrigin", "transform-origin"),
    ("underlinePosition", "underline-position"),
    ("underlineThickness", "underline-thickness"),
    ("unicodeBidi", "unicode-bidi"),
    ("unicodeRange", "unicode-range"),
    ("unitsPerEm", "units-per-em"),
    ("vAlphabetic", "v-alphabetic"),
    ("vHanging", "v-hanging"),
    ("vIdeographic", "v-ideographic"),
    ("vMathematical", "v-mathematical"),
    ("vectorEffect", "vector-effect"),
    ("vertAdvY", "vert-adv-y"),
    ("vertOriginX", "vert-origin-x"),
    ("vertOriginY", "vert-origin-y"),
    ("viewBox", "viewBox"),
    ("viewTarget", "viewTarget"),
    ("wordSpacing", "word-spacing"),
    ("writingMode", "writing-mode"),
    ("xChannelSelector", "xChannelSelector"),
    ("xHeight", "x-height"),
    ("xlinkActuate", "xlink:actuate"),
    ("xlinkArcrole", "xlink:arcrole"),
    ("xlinkHref", "xlink:href"),
    ("xlinkRole", "xlink:role"),
    ("xlinkShow", "xlink:show"),
    ("xlinkTitle", "xlink:title"),
    ("xlinkType", "xlink:type"),
    ("xmlBase", "xml:base"),
    ("xmlLang", "xml:lang"),
    ("xmlSpace", "xml:space"),
    ("xmlnsXlink", "xmlns:xlink"),
    ("yChannelSelector", "yChannelSelector"),
    ("zoomAndPan", "zoomAndPan"),
];

pub(crate) fn serialized_standard_attr(name: &str) -> Option<&'static str> {
    STANDARD_ATTRS
        .binary_search_by_key(&name, |(canonical, _)| canonical)
        .ok()
        .map(|index| STANDARD_ATTRS[index].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn standard_attrs_are_strictly_sorted_and_unique() {
        for pair in STANDARD_ATTRS.windows(2) {
            assert!(
                pair[0].0 < pair[1].0,
                "standard attribute table must be strictly sorted: {:?} then {:?}",
                pair[0],
                pair[1]
            );
        }
    }
}
