//! Emit IR → Rust source containing `maud::html!` macro invocations.
//!
//! Determinism is load-bearing: T8 will compare the output byte-for-byte
//! against committed golden fixtures, so every emit decision must be a pure
//! function of the IR. In particular:
//!
//! - `Props` struct fields are emitted in `props.bindings` order (declaration
//!   order from the user's destructured-param shape).
//! - Nested struct fields use `BTreeMap` order (alphabetical).
//! - Nested struct DECLARATIONS are emitted depth-first (deepest type first)
//!   so spec §10.3 (`ItemsItem` before `Props`) matches.

use std::fmt::Write;

use crate::ir::*;

pub fn emit(component: &Component) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "// === GENERATED by jsx-rust-compiler; do not edit. ==="
    );
    let _ = writeln!(out, "use maud::{{html, Markup}};");
    let _ = writeln!(out);
    emit_struct_decls(&component.props, &mut out);
    emit_render_fn(component, &mut out);
    out
}

/// Emit all generated `pub struct` declarations.
///
/// Order (matches spec §10.3 byte-equality requirement):
/// 1. Each top-level prop's nested types — deepest struct first, then its
///    enclosing struct, etc. (depth-first post-order).
/// 2. `pub struct Props { … }` last, with fields in `bindings` declaration
///    order.
fn emit_struct_decls(props: &PropsShape, out: &mut String) {
    // 1. Emit nested struct types, depth-first.
    //    Walk in `BTreeMap` (alphabetical) order over prop names for deterministic
    //    ordering when multiple top-level props each carry struct types.
    for (root_name, ty) in &props.types {
        emit_nested_decls_for(root_name, ty, out);
    }

    // 2. Props struct itself — fields in declaration order from `bindings`.
    emit_props_struct(props, out);
}

/// Recursively emit struct declarations for a single top-level prop's type.
///
/// `path_pascal` is the PascalCase struct name at this level. The caller
/// passes the root prop name (already PascalCased one level up) and we
/// concatenate any deeper segments.
fn emit_nested_decls_for(root_name: &str, ty: &PropType, out: &mut String) {
    let root_pascal = pascal_case(root_name);
    emit_nested_decls_walk(&root_pascal, ty, out);
}

fn emit_nested_decls_walk(name_pascal: &str, ty: &PropType, out: &mut String) {
    match ty {
        PropType::OwnedString => {
            // Leaf — no struct declaration emitted here. The enclosing struct
            // (if any) declares this as a `String` field.
        }
        PropType::VecOf(inner) => {
            // The element type's struct name is `<name_pascal>Item`
            // (e.g. `items` → `ItemsItem`).
            let item_name = format!("{name_pascal}Item");
            emit_nested_decls_walk(&item_name, inner, out);
        }
        PropType::Struct(fields) => {
            // Depth-first: emit child structs FIRST, then this one.
            for (field_name, field_ty) in fields {
                let child_name = format!("{name_pascal}{}", pascal_case(field_name));
                emit_nested_decls_walk(&child_name, field_ty, out);
            }
            // Now emit `pub struct <name_pascal> { ... }`.
            let _ = writeln!(out, "pub struct {name_pascal} {{");
            for (field_name, field_ty) in fields {
                let rust_ty = rust_type_for(name_pascal, field_name, field_ty);
                let _ = writeln!(out, "    pub {field_name}: {rust_ty},");
            }
            let _ = writeln!(out, "}}");
            let _ = writeln!(out);
        }
    }
}

/// Determine the Rust type string for a field nested inside a parent struct.
///
/// `parent_pascal` is the PascalCase name of the enclosing struct; `field_name`
/// is this field's lowercase name; `ty` is its type.
fn rust_type_for(parent_pascal: &str, field_name: &str, ty: &PropType) -> String {
    match ty {
        PropType::OwnedString => "String".to_string(),
        PropType::Struct(_) => format!("{parent_pascal}{}", pascal_case(field_name)),
        PropType::VecOf(inner) => {
            let item_name = format!("{parent_pascal}{}Item", pascal_case(field_name));
            // The inner type of a Vec is always referenced by name. For a
            // VecOf(Struct) the struct is `<item_name>`; for a VecOf(OwnedString)
            // it's `String` etc. — but only Struct is exercised in A1 fixtures.
            match inner.as_ref() {
                PropType::Struct(_) => format!("Vec<{item_name}>"),
                PropType::OwnedString => "Vec<String>".to_string(),
                PropType::VecOf(_) => format!("Vec<{item_name}>"), // nested vec — A1 doesn't produce this
            }
        }
    }
}

/// Emit the top-level `pub struct Props { … }`.
fn emit_props_struct(props: &PropsShape, out: &mut String) {
    if props.bindings.is_empty() {
        let _ = writeln!(out, "pub struct Props {{}}");
    } else {
        let _ = writeln!(out, "pub struct Props {{");
        for name in &props.bindings {
            let ty = props.types.get(name);
            let rust_ty = match ty {
                Some(PropType::OwnedString) | None => "String".to_string(),
                Some(PropType::Struct(_)) => pascal_case(name),
                Some(PropType::VecOf(inner)) => match inner.as_ref() {
                    PropType::Struct(_) => format!("Vec<{}Item>", pascal_case(name)),
                    PropType::OwnedString => "Vec<String>".to_string(),
                    PropType::VecOf(_) => format!("Vec<{}Item>", pascal_case(name)),
                },
            };
            let _ = writeln!(out, "    pub {name}: {rust_ty},");
        }
        let _ = writeln!(out, "}}");
    }
    let _ = writeln!(out);
}

/// Emit the `pub fn render(...) -> Markup { html! { … } }` block.
fn emit_render_fn(component: &Component, out: &mut String) {
    let param_name = if component.props.bindings.is_empty() {
        "_props"
    } else {
        "props"
    };
    let _ = writeln!(out, "pub fn render({param_name}: &Props) -> Markup {{");
    let _ = writeln!(out, "    html! {{");
    emit_node(&component.root, 2, out);
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
}

/// Emit one IR node, indented by `indent` levels of 4 spaces.
fn emit_node(node: &JsxNode, indent: usize, out: &mut String) {
    let pad = "    ".repeat(indent);
    match node {
        JsxNode::Empty => {}
        JsxNode::Text(s) => {
            let _ = writeln!(out, "{pad}{}", rust_string_literal(s));
        }
        JsxNode::Expr(e) => {
            let _ = writeln!(out, "{pad}({})", emit_expr(e));
        }
        JsxNode::Map {
            source,
            binding,
            body,
        } => {
            let _ = writeln!(
                out,
                "{pad}@for {binding} in &{} {{",
                emit_expr_collection(source)
            );
            emit_node(body, indent + 1, out);
            let _ = writeln!(out, "{pad}}}");
        }
        JsxNode::Element {
            tag,
            attrs,
            children,
        } => {
            // Build the tag + inline attrs prefix.
            let mut line = format!("{pad}{tag}");
            for a in attrs {
                emit_attr(a, &mut line);
            }
            if is_void(tag) {
                // Void elements terminate with `;`. Children are already
                // rejected by the lowerer; we don't need to handle them here.
                let _ = writeln!(out, "{line};");
            } else {
                let _ = writeln!(out, "{line} {{");
                for c in children {
                    emit_node(c, indent + 1, out);
                }
                let _ = writeln!(out, "{pad}}}");
            }
        }
    }
}

/// Emit a single attribute appended to `line`.
///
/// - `Empty` → bare ` name` (boolean attribute).
/// - `Static(s)` → ` name="<s>"` as a Rust string literal (maud escapes at render).
/// - `StaticNum(n)` → ` name=(<n>)` — emits as an i64 expression, NOT a string.
/// - `Expr(e)` → ` name=(<emit_expr>)`.
fn emit_attr(a: &JsxAttr, line: &mut String) {
    match &a.value {
        AttrValue::Empty => {
            let _ = write!(line, " {}", a.name);
        }
        AttrValue::Static(s) => {
            let _ = write!(line, " {}={}", a.name, rust_string_literal(s));
        }
        AttrValue::StaticNum(n) => {
            let _ = write!(line, " {}=({n})", a.name);
        }
        AttrValue::Expr(e) => {
            let _ = write!(line, " {}=({})", a.name, emit_expr(e));
        }
    }
}

/// Render an IR expression as the Rust source that goes inside a maud `(…)`.
fn emit_expr(e: &Expr) -> String {
    match e {
        Expr::Field(name) => format!("props.{name}"),
        Expr::MemberAccess { root, path } => format!("props.{root}.{}", path.join(".")),
        Expr::MapBinding(name) => name.clone(),
        Expr::MapMember { root, path } => format!("{root}.{}", path.join(".")),
        Expr::StaticText(s) => rust_string_literal(s),
        Expr::StaticNum(n) => n.to_string(),
    }
}

/// Render an IR expression specifically as a `@for x in &<here>` collection target.
///
/// For `Field(name)`/`MemberAccess` this is identical to `emit_expr`; for
/// anything else we fall back to `emit_expr` (the lowerer rejects unsupported
/// shapes, so the fallback is mostly for completeness).
fn emit_expr_collection(e: &Expr) -> String {
    match e {
        Expr::Field(name) => format!("props.{name}"),
        Expr::MemberAccess { root, path } => format!("props.{root}.{}", path.join(".")),
        other => emit_expr(other),
    }
}

/// Format a string as a Rust string literal with proper escaping.
///
/// Using `{:?}` would produce e.g. `"hi & co"` which is fine, but `{:?}` also
/// escapes characters maud handles natively, and emits `\"` for `"` which is
/// always correct. The Debug formatter for `str` already produces a valid
/// Rust string literal, so we delegate.
fn rust_string_literal(s: &str) -> String {
    format!("{s:?}")
}

const VOID: &[&str] = &[
    "area", "base", "br", "col", "embed", "hr", "img", "input", "keygen", "link", "meta", "param",
    "source", "track", "wbr",
];

fn is_void(tag: &str) -> bool {
    VOID.contains(&tag)
}

/// Convert a lowercase identifier (`items`, `user_address`) to PascalCase
/// (`Items`, `UserAddress`).
///
/// Handles snake_case (`_` splits) and treats hyphen as a splitter too for
/// safety. For A1 fixtures only the simple capitalize-first-char case is
/// exercised.
fn pascal_case(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut capitalize_next = true;
    for c in s.chars() {
        if c == '_' || c == '-' {
            capitalize_next = true;
        } else if capitalize_next {
            for up in c.to_uppercase() {
                out.push(up);
            }
            capitalize_next = false;
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use crate::compile;

    /// End-to-end compile helper — easier than hand-building IR.
    fn must_compile(src: &str) -> String {
        compile(src).unwrap_or_else(|e| panic!("compile failed: {e}"))
    }

    #[test]
    fn emits_empty_props_struct_for_zero_prop_component() {
        let out = must_compile(
            r#"export default function StaticHello() {
  return <div>"hi"</div>;
}"#,
        );
        // Header + use + empty Props + render with `_props`.
        assert!(
            out.contains("// === GENERATED by jsx-rust-compiler; do not edit. ==="),
            "missing generated header: {out}"
        );
        assert!(
            out.contains("use maud::{html, Markup};"),
            "missing maud import: {out}"
        );
        assert!(
            out.contains("pub struct Props {}"),
            "missing empty Props struct: {out}"
        );
        assert!(
            out.contains("pub fn render(_props: &Props) -> Markup {"),
            "expected `_props` for zero-prop component: {out}"
        );
        assert!(out.contains("html! {"), "missing html! block opener: {out}");
        assert!(out.contains("div {"), "missing div block: {out}");
    }

    #[test]
    fn emits_attr_with_static_value() {
        let out = must_compile(
            r#"export default function X() {
  return <a href="/x"/>;
}"#,
        );
        // Self-closing non-void `<a/>` becomes block form in maud.
        // The attr `href="/x"` emits as `href="/x"`.
        assert!(
            out.contains(r#"a href="/x""#),
            "missing `a href=\"/x\"` shape: {out}"
        );
    }

    #[test]
    fn emits_attr_with_expr_value() {
        // Use a `.map` to get an iter-binding in scope, then reference
        // `item.href` as an attr expr value.
        let out = must_compile(
            r#"export default function ListNav({ items }) {
  return <ul>{items.map((item) => (<li><a href={item.href}>{item.label}</a></li>))}</ul>;
}"#,
        );
        // The href attr should emit as `href=(item.href)`.
        assert!(
            out.contains("href=(item.href)"),
            "expected `href=(item.href)`: {out}"
        );
    }

    #[test]
    fn emits_text_node_escaped_literal() {
        // The JSX text "hi" lowers to `Text("hi")` and emits as the literal `"hi"`.
        // The text "hi & co" comes through a string-literal expr container.
        let out = must_compile(
            r#"export default function X() {
  return <p>{"hi & co"}</p>;
}"#,
        );
        // String-literal expr emits as `("hi & co")`.
        assert!(
            out.contains(r#"("hi & co")"#),
            "missing escaped string literal: {out}"
        );
    }

    #[test]
    fn emits_for_loop_for_map_node() {
        let out = must_compile(
            r#"export default function ListNav({ items }) {
  return <ul>{items.map((item) => (<li>{item.label}</li>))}</ul>;
}"#,
        );
        // @for emits with `&props.items` source.
        assert!(
            out.contains("@for item in &props.items {"),
            "missing @for block: {out}"
        );
        // The body references the map binding.
        assert!(
            out.contains("(item.label)"),
            "missing item.label body: {out}"
        );
        // The generated `ItemsItem` struct appears.
        assert!(
            out.contains("pub struct ItemsItem {"),
            "missing ItemsItem struct: {out}"
        );
        // And the Props struct references Vec<ItemsItem>.
        assert!(
            out.contains("pub items: Vec<ItemsItem>,"),
            "missing items field: {out}"
        );
    }
}
