// The one seam between the TS package and the napi addon (`../native/index.js`, generated by
// `napi build`). Loaded lazily so importing `@brust/core` never needs the addon (a route file is
// imported by `brust build` and by tests); tests swap the binding with `setNative` instead of
// `mock.module`, which leaks process-wide.

/** Shapes of `crates/brust-napi` (plan D1, Task 1 + Task 2). Written by hand so this file
 * typechecks before Task 2's exports exist in the generated `native/index.d.ts`. */
export interface InvalidateArgs {
  key?: string
  tags?: string[]
  path?: string
  method?: string
}
export interface InvalidateResult {
  l1Removed: number
  jobRemoved: number
}
export interface StartOptions {
  host: string
  port: number
  distDir: string
  workers: number
  claimTimeoutMs?: number
  callTimeoutMs?: number
  l1Capacity?: number
  jobCacheCapacity?: number
  generator?: string
}
export type WorkerFn = (kind: 'loader' | 'jobs', requestJson: string, slot: number) => Promise<number>
export interface NativeBinding {
  startServer(opts: StartOptions): void
  registerWorker(buf: Uint8Array, slots: number, f: WorkerFn): number
  untilReady(timeoutMs: number): Promise<void>
  beginDrain(timeoutMs: number): Promise<void>
  cacheInvalidate(args: InvalidateArgs): InvalidateResult
  cacheStats(): string
  localAddr(): string
}

let binding: NativeBinding | null = null

/** The addon, loaded on first use. Throws if the addon is not built for this platform. */
export function native(): NativeBinding {
  binding ??= require('../native/index.js') as NativeBinding
  return binding
}

/** Replace the binding (tests). Returns the previous one so a test can restore it;
 * `null` restores lazy loading. */
export function setNative(b: NativeBinding | null): NativeBinding | null {
  const prev = binding
  binding = b
  return prev
}

export const startServer = (opts: StartOptions): void => native().startServer(opts)
export const registerWorker = (buf: Uint8Array, slots: number, f: WorkerFn): number => native().registerWorker(buf, slots, f)
export const untilReady = (timeoutMs: number): Promise<void> => native().untilReady(timeoutMs)
export const beginDrain = (timeoutMs: number): Promise<void> => native().beginDrain(timeoutMs)
export const cacheInvalidate = (args: InvalidateArgs): InvalidateResult => native().cacheInvalidate(args)
export const cacheStats = (): string => native().cacheStats()
export const localAddr = (): string => native().localAddr()
