// generated by brust v2 — precompute job for input_cabc2a77; pure function of its inputs
import { take } from "./take"
export const inputs = ["rows"] as const
export function precompute(props: any) {
  const { rows } = props
  const n = 1
  const shown = take(rows, n)
  return { _s1: shown }
}
