// generated by brust v2 — client chunk for badge_586b3854
import { computed, defineBehavior } from "brust/runtime-dom"
const __attr = (v) => (v === false ? null : v)
const __unitless = new Set(["zIndex", "opacity", "flex", "flexGrow", "flexShrink", "fontWeight", "lineHeight", "order", "zoom"])
const __css = (o) => Object.entries(o !== null && typeof o === "object" ? o : {})
  .filter(([k, v]) => v != null && v !== false && /^(--[A-Za-z0-9_-]+|[A-Za-z][A-Za-z0-9_-]*)$/.test(k))
  .map(([k, v]) => [k, typeof v === "number" ? (v === 0 || __unitless.has(k) || k.startsWith("--") ? String(v) : v + "px") : typeof v === "boolean" ? "" : String(v)])
  .filter(([, v]) => v !== "" && !/[;{}\\\n\r]|\/\*|expression\(|@import/i.test(v))
  .map(([k, v]) => (k.startsWith("--") ? k : k.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase())) + ":" + v)
  .join(";")
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("badge_586b3854", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _c1 = computed(() => __attr(props().type))
  const _c2 = computed(() => __css({ background: props().color }))
  const _c3 = computed(() => __text(props().label))
  return { _c1, _c2, _c3 }
})
