// generated by brust v2 — client chunk for input_cabc2a77
import { signal, computed, defineBehavior } from "brust/runtime-dom"
import { take } from "./take"
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("input_cabc2a77", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const n = signal(1)
  const shown = computed(() => take(props().rows, n()))
  const _h1 = (...a) => (() => n.set(n() + 1))(...a)
  const _l1 = computed(() => shown())
  const _k1 = (p) => p.id
  const _c1 = (p) => __text(p.num)
  const _l2 = (p) => p.badges
  const _k2 = (b) => b.type
  const _p1 = (p, b) => ({ type: b.type, label: b.label, color: b.color })
  return { n, _h1, _l1, _k1, _c1, _l2, _k2, _p1 }
})
