// generated by brust v2 — client chunk for input_18a4a322
import { signal, computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_18a4a322", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const selected = signal(null)
  const _l1 = computed(() => props().todos)
  const _k1 = (t) => t.id
  const _p1 = (t) => ({ title: t.title, selected: t.id === selected(), onPick: () => selected.set(t.id) })
  return { selected, _l1, _k1, _p1 }
})
