// === GENERATED by jsx-rust-compiler; do not edit. ===
use maud::{html, Markup};

pub struct ItemsItem {
    pub href: String,
    pub label: String,
}

pub struct Props {
    pub items: Vec<ItemsItem>,
}

pub fn render(props: &Props) -> Markup {
    html! {
        nav {
            ul {
                @for item in &props.items {
                    li {
                        a href=(item.href) {
                            (item.label)
                        }
                    }
                }
            }
        }
    }
}
