// === GENERATED by jsx-rust-compiler; do not edit. ===
use maud::{Markup, html};

pub struct Props {
    pub title: String,
    pub body: String,
}

pub fn render(props: &Props) -> Markup {
    html! {
        article {
            h1 {
                (props.title)
            }
            p {
                (props.body)
            }
        }
    }
}
