// === GENERATED by jsx-rust-compiler; do not edit. ===
use maud::{html, Markup};

pub struct Props {}

pub fn render(_props: &Props) -> Markup {
    html! {
        div {
            h1 {
                "Hello from compiled Rust"
            }
            p {
                "This page is statically generated."
            }
        }
    }
}
