// generated by brust v2 — client chunk for list_4d8da56b
import { computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("list_4d8da56b", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _l1 = computed(() => props().rows)
  const _k1 = (r) => r.id
  const _p1 = (r) => ({ label: r.name })
  return { _l1, _k1, _p1 }
})
