// generated by brust v2 — client chunk for badge_4ab66d34
import { computed, defineBehavior } from "brust/runtime-dom"
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("badge_4ab66d34", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _c1 = computed(() => __text(props().label))
  return { _c1 }
})
