//! M1c Task 5: the precompute job module.
mod lower_common;
use lower_common::{fixture_artifacts, lower};

#[test]
fn product_card_job() {
    let a = lower(
        &std::fs::read_to_string(
            lower_common::repo().join("tests/fixtures/product-card/input.tsx"),
        )
        .unwrap(),
    );
    assert_eq!(
        a.server_ts.unwrap(),
        "// generated by brust v2 — precompute job for t_a5b35add; pure function of its inputs\nimport { formatPrice } from \"./money\"\nexport const inputs = [\"item.price\"] as const\nexport function precompute(props: any) {\n  const { item } = props\n  const qty = 1\n  const unit = formatPrice(item.price)\n  const total = formatPrice(item.price * qty)\n  return { _s1: unit, _s2: total }\n}\n"
    );
}

/// M1c inputs 1, 2 and 4: module helpers, slot-local functions, nested lists.
#[test]
fn helpers_and_nested_lists() {
    let job = lower(
        "import { fmt } from './money'\nconst RATE = 2\nexport default function L({ items, title: heading }: any) {\n  const scale = (x: number) => x * RATE\n  return <ul title={heading}>{items.map((o: any, oi: number) => <li key={o.id}>{o.rows.map((r: any) => <b key={r}>{fmt(scale(r) + oi)}</b>)}</li>)}</ul>\n}",
    )
    .server_ts
    .unwrap();
    assert!(job.contains("\nconst RATE = 2;\n"), "{job}");
    assert!(job.contains("  const scale = (x) => x * RATE\n"), "{job}");
    assert!(
        job.contains(
            "return { _s1: (items).map((o, oi) => (o.rows).map((r) => fmt(scale(r) + oi))) }"
        ),
        "{job}"
    );
}

/// A renamed prop read by opaque code keeps its local name bound.
#[test]
fn renamed_props_are_destructured_by_local() {
    let job = lower(
        "export default function L({ title: heading }: any) { return <p>{new Date(heading).getTime()}</p> }",
    )
    .server_ts
    .unwrap();
    assert!(job.contains("const { title: heading } = props"), "{job}");
}

/// Spec §11 job purity: no browser global or request accessor in any job.
#[test]
fn jobs_are_pure() {
    let banned = [
        "window",
        "document",
        "navigator",
        "localStorage",
        "sessionStorage",
        "location",
        "history",
        "req",
        "request",
        "cookies",
        "headers",
    ];
    let mut checked = 0;
    for (name, a) in fixture_artifacts() {
        let Some(job) = a.server_ts else { continue };
        checked += 1;
        for b in banned {
            let found = job
                .split(|c: char| !(c.is_ascii_alphanumeric() || c == '_' || c == '$'))
                .any(|w| w == b);
            assert!(!found, "{name}: job reads `{b}`\n{job}");
        }
    }
    assert!(checked >= 2);
}
