//! M1c Task 5: the precompute job module.
mod lower_common;
use lower_common::{fixture_artifacts, lower};

#[test]
fn product_card_job() {
    let a = lower(
        &std::fs::read_to_string(
            lower_common::repo().join("tests/fixtures/product-card/input.tsx"),
        )
        .unwrap(),
    );
    assert_eq!(
        a.server_ts.unwrap(),
        "// generated by brust v2 — precompute job for t_a5b35add; pure function of its inputs\nimport { formatPrice } from \"./money\"\nexport const inputs = [\"item.price\"] as const\nexport function precompute(props: any) {\n  const { item } = props\n  const qty = 1\n  const unit = formatPrice(item.price)\n  const total = formatPrice(item.price * qty)\n  return { _s1: unit, _s2: total }\n}\n"
    );
}

/// M1c inputs 1, 2 and 4: module helpers, slot-local functions, nested lists.
#[test]
fn helpers_and_nested_lists() {
    let job = lower(
        "import { fmt } from './money'\nconst RATE = 2\nexport default function L({ items, title: heading }: any) {\n  const scale = (x: number) => x * RATE\n  return <ul title={heading}>{items.map((o: any, oi: number) => <li key={o.id}>{o.rows.map((r: any) => <b key={r}>{fmt(scale(r) + oi)}</b>)}</li>)}</ul>\n}",
    )
    .server_ts
    .unwrap();
    assert!(job.contains("\nconst RATE = 2;\n"), "{job}");
    assert!(job.contains("  const scale = (x) => x * RATE\n"), "{job}");
    assert!(
        job.contains(
            "return { _s1: (items).map((o, oi) => (o.rows).map((r) => fmt(scale(r) + oi))) }"
        ),
        "{job}"
    );
}

/// A renamed prop read by opaque code keeps its local name bound.
#[test]
fn renamed_props_are_destructured_by_local() {
    let job = lower(
        "export default function L({ title: heading }: any) { return <p>{new Date(heading).getTime()}</p> }",
    )
    .server_ts
    .unwrap();
    assert!(job.contains("const { title: heading } = props"), "{job}");
}

/// Spec §11 job purity: no browser global or request accessor in any job.
#[test]
fn jobs_are_pure() {
    let banned = [
        "window",
        "document",
        "navigator",
        "localStorage",
        "sessionStorage",
        "location",
        "history",
        "req",
        "request",
        "cookies",
        "headers",
    ];
    let mut checked = 0;
    for (name, a) in fixture_artifacts() {
        let Some(job) = a.server_ts else { continue };
        checked += 1;
        for b in banned {
            let found = job
                .split(|c: char| !(c.is_ascii_alphanumeric() || c == '_' || c == '$'))
                .any(|w| w == b);
            assert!(!found, "{name}: job reads `{b}`\n{job}");
        }
    }
    assert!(checked >= 2);
}

/// F67: every declared output slot is present in the job result, `null` under a false guard.
#[test]
fn every_output_slot_is_present_even_when_its_guard_is_false() {
    let root = lower_common::repo();
    let (_, a) = fixture_artifacts()
        .into_iter()
        .find(|(_, a)| {
            a.server_ts
                .as_deref()
                .is_some_and(|s| s.contains("_s4:") && s.contains("(a && b)"))
        })
        .expect("guarded-slot job");
    let dir = std::env::temp_dir().join(format!("brustc-guarded-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    std::fs::copy(
        root.join("tests/fixtures/guarded-slot/money.ts"),
        dir.join("money.ts"),
    )
    .unwrap();
    std::fs::write(dir.join("job.server.ts"), a.server_ts.unwrap()).unwrap();
    let out = std::process::Command::new("bun")
        .arg(root.join("crates/brust-compiler/tests/harness/eval.ts"))
        .args(["slots"])
        .arg(dir.join("job.server.ts"))
        .arg(root.join("tests/fixtures/guarded-slot/sample-props.json"))
        .output()
        .expect("bun");
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let result: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let ir: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(root.join("tests/fixtures/guarded-slot/expected.ir.json"))
            .unwrap(),
    )
    .unwrap();
    let outputs: Vec<String> = ir["jobs"][0]["outputs"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_str().unwrap().to_string())
        .collect();
    assert!(outputs.len() >= 4, "{outputs:?}");
    for slot in &outputs {
        assert!(result.get(slot).is_some(), "slot {slot} missing: {result}");
    }
    let o = |i: usize| &result[&outputs[i]];
    assert!(o(0).is_null(), "prop guard false -> null: {result}");
    let rows = o(2).as_array().expect("per-row slot is an array");
    assert_eq!(rows.len(), 2);
    assert!(rows[0].is_null() && !rows[1].is_null(), "{rows:?}");
    assert!(
        o(1).is_null() && o(3).is_null(),
        "state guard / nested guard false -> null: {result}"
    );
}
