// generated by brust v2 — client chunk for input_d4c7015a
import { signal, computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_d4c7015a", ({ el, props, effect, onCleanup, ref }) => {
  const selected = signal(null)
  const _h1 = (todo, i, ...a) => (() => selected.set(todo.id))(...a)
  const _l1 = computed(() => props().todos)
  const _k1 = (todo) => todo.id
  const _c1 = (todo) => todo.id === selected() ? "selected" : ""
  const _c2 = (i) => i + 1
  const _c3 = (todo) => todo.title
  const _c4 = (todo) => todo.done
  return { selected, _h1, _l1, _k1, _c1, _c2, _c3, _c4 }
})
