// generated by brust v2 — client chunk for input_8803b8a9
import { signal, computed, defineBehavior } from "brust/runtime-dom"
import { readFileSync } from "node:fs"
export default defineBehavior("input_8803b8a9", ({ el, props, effect, onCleanup, ref }) => {
  const text = signal("")
  const _h1 = (...a) => (() => text.set(readFileSync(props().path, "utf8")))(...a)
  const _c1 = computed(() => text())
  return { text, _h1, _c1 }
})
