// generated by brust v2 — client chunk for input_403bf43c
import { signal, computed, untracked, defineBehavior } from "brust/runtime-dom"
const __attr = (v) => (v === false ? null : v)
const __unitless = new Set(["zIndex", "opacity", "flex", "flexGrow", "flexShrink", "fontWeight", "lineHeight", "order", "zoom"])
const __css = (o) => Object.entries(o ?? {})
  .filter(([, v]) => v != null && v !== false)
  .map(([k, v]) => [k, typeof v === "number" ? (v === 0 || __unitless.has(k) || k.startsWith("--") ? String(v) : v + "px") : typeof v === "boolean" ? "" : String(v)])
  .filter(([, v]) => v !== "" && !/[;{}\\\n\r]|\/\*|expression\(|@import/i.test(v))
  .map(([k, v]) => (k.startsWith("--") ? k : k.replace(/[A-Z]/g, (c) => "-" + c.toLowerCase())) + ":" + v)
  .join(";")
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("input_403bf43c", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const on = signal(false)
  const ref = __ref("ref")
  const _h1 = (...a) => (() => on.set(!on()))(...a)
  const _c1 = computed(() => __attr(on() && "on"))
  const _c2 = computed(() => __css({ color: on() ? "red" : "blue", fontSize: (props()["size"] === undefined ? 3 : props()["size"]), opacity: on() ? 1 : 0.5 }))
  const _c3 = computed(() => __text(on() && "Loading"))
  const _c4 = computed(() => __text((props()["size"] === undefined ? 3 : props()["size"]) * 2))
  const _c5 = computed(() => __attr(props().label))
  const _c6 = computed(() => __text(props().label ?? "none"))
  __effect(() => { void [on()]; return untracked(() => (((on) => (() => {
  document.title = String(on);
}))(on()))()) })
  return { on, _h1, _c1, _c2, _c3, _c4, _c5, _c6 }
})
