// scripts/m2-exit/exit.ts — the M2 exit report (spec §10): pinned sets + computed prose, no hand-written claims.
export interface ManifestLike { routes: { id: string; pattern: string; chain: string[]; cache: unknown }[]; components: Record<string, { tier: string; jobs: { kind: string }[]; children: unknown[]; client: string | null; use_id_slots: number }> }
export interface BenchLike { date: string; host: string; bun: string; conn: number; dur: string; bar: string; probes: { id: string; path: string; v2: { rps: number; p99: number }; x01: { rps: number; p99: number } | null; v2Gzip: { rps: number }; x01Gzip: { rps: number } | null; deltaRpsPct: number | null }[] }
export interface LedgerRow { id: string; where: string; finding: string; owner: string; state: 'closed' | 'open' }
export interface ExitInputs { manifest: ManifestLike; bench: BenchLike; ledger: LedgerRow[]; ledger68: LedgerRow; runtimeDomPublishable: boolean }

export const ROUTES = [
  { pattern: '/', leafTier: 'native', why: 'HeroSearch (useState + useId); per-row TypeBadge jobs; TeamBuilder island from the layout' },
  { pattern: '/pokedex', leafTier: 'static', why: 'native DexFilter child (useState) over keyed DexCard rows; loader reads ?q=' },
  { pattern: '/pokemon/{name}', leafTier: 'native', why: 'own precompute job (fmtHeight/fmtWeight); per-row TypeBadge; notFound verdict; L1 60 s tag pokemon; bypass query(nocache)' },
  { pattern: '/type-chart', leafTier: 'static', why: 'nested .map() grid; L1 3600 s tag types' },
  { pattern: '*', leafTier: 'static', why: 'own <html> document outside the layout: 0 Bun calls, no scripts' },
] as const
export const PROBES = [{ id: 'A-static-hit' }, { id: 'B-native-miss' }, { id: 'C-react-child' }] as const
export const LEDGER_RANGE = Array.from({ length: 18 }, (_, i) => 32 + i)          // F32..F49
/** Rows whose owner column starts with DONE at the time this lane closes (the test fails if reality differs). */
export const MUST_BE_CLOSED = ['F32', 'F33', 'F34', 'F35', 'F37', 'F38', 'F39', 'F40', 'F41', 'F42', 'F45', 'F49']
/** Rows spec §10 lists that may remain re-filed with a reason in the owner column. */
export const MAY_BE_REFILED: string[] = []

/** The ledger table rows `| F<n> | where | finding | fix | owner |`; state = owner column starts with `DONE`. */
export function parseLedger(md: string, ids: number[]): LedgerRow[] {
  const out: LedgerRow[] = []
  for (const n of ids) {
    const line = md.split('\n').find((l) => l.startsWith(`| F${n} |`))
    if (!line) throw new Error(`ledger row F${n} missing`)
    const cells = line.split('|').slice(1, -1).map((c) => c.trim())
    const [id, where, finding, , owner] = cells as [string, string, string, string, string]
    out.push({ id, where, finding, owner, state: owner.startsWith('DONE') ? 'closed' : 'open' })
  }
  return out
}

export function renderExitReport(i: ExitInputs): string {
  const L: string[] = []
  const comps = Object.entries(i.manifest.components)
  const n = (f: (c: ManifestLike['components'][string]) => boolean) => comps.filter(([, c]) => f(c)).length
  L.push('# M2 exit report', '', 'Generated by `bun scripts/m2-exit/run.ts`; do not edit. Criteria are spec §10; `bun test scripts/m2-exit` checks them by code.', '')
  L.push('## Dogfood (`examples/pokedex`)', '')
  L.push(`- ${i.manifest.routes.length} routes served by \`brust start\` from \`dist/manifest.json\`; ${comps.length} compiled components: ${n((c) => c.tier === 'static')} static, ${n((c) => c.tier === 'native')} native, ${n((c) => c.tier === 'react')} react; ${comps.reduce((a, [, c]) => a + c.jobs.length, 0)} job records (${comps.reduce((a, [, c]) => a + c.jobs.filter((j) => j.kind === 'ssr').length, 0)} ssr); ${comps.reduce((a, [, c]) => a + c.children.length, 0)} inlined child instance records; ${comps.reduce((a, [, c]) => a + c.use_id_slots, 0)} useId slot(s).`, '')
  L.push('| Route | Leaf tier | Chain | Cache | Exercises |', '|---|---|---|---|---|')
  for (const r of ROUTES) {
    const m = i.manifest.routes.find((x) => x.pattern === r.pattern)!
    L.push(`| \`${r.pattern}\` | ${i.manifest.components[m.chain[m.chain.length - 1]!]!.tier} | ${m.chain.join(' → ')} | ${m.cache ? JSON.stringify(m.cache) : '—'} | ${r.why} |`)
  }
  L.push('', '## Integration (`tests/server/pokedex.test.ts`, `hydrate.chromium.test.ts`)', '', 'Every route 200 with expected text; `notFound` → 404 never cached; L1 HIT with `loader_calls` unchanged; `?nocache=1` bypass; job-cache HIT across `/` → `/pokemon/pikachu` (`job.hits` ≥ 2, `job.misses` = 1); per-row child values in row order; `useId` identical across requests; the catch-all makes 0 Bun calls and ships no script; the react child hydrates in Chromium with no console error and is interactive.', '')
  L.push('## Bench (`bench/RESULTS.json`)', '', `Measured ${i.bench.date} on ${i.bench.host}, Bun ${i.bench.bun}, \`oha -c ${i.bench.conn} -z ${i.bench.dur}\`. **Bar (v2 not slower on any probe, \`Accept-Encoding: identity\` on both sides): ${i.bench.bar}.** The gzip columns are an extra.`, '', '| Probe | Path | v2 rps | 0.1.x rps | Δ | v2 gzip rps | 0.1.x gzip rps |', '|---|---|---:|---:|---:|---:|---:|')
  for (const p of i.bench.probes) L.push(`| ${p.id} | \`${p.path}\` | ${Math.round(p.v2.rps).toLocaleString()} | ${p.x01 ? Math.round(p.x01.rps).toLocaleString() : '—'} | ${p.deltaRpsPct === null ? 'not measured' : `${p.deltaRpsPct}%`} | ${Math.round(p.v2Gzip.rps).toLocaleString()} | ${p.x01Gzip ? Math.round(p.x01Gzip.rps).toLocaleString() : '—'} |`)
  if (i.bench.bar !== 'met') L.push('', `**M2 is not complete:** the bar is ${i.bench.bar}; ledger F68 (lane \`m2p-render-perf\`) must close with the bar met.`)
  L.push('', '## Ledger F32–F49', '', `${i.ledger.filter((r) => r.state === 'closed').length} closed, ${i.ledger.filter((r) => r.state === 'open').length} re-filed (owner column of \`docs/plans/m1a-followups.md\`).`, '', '| Id | State | Owner / reason |', '|---|---|---|')
  for (const r of i.ledger) L.push(`| ${r.id} | ${r.state} | ${r.owner} |`)
  L.push('', '## Publish', '', `\`release.yml\` builds six targets and dry-runs \`bun publish\` for \`@brust/core\`, ${i.runtimeDomPublishable ? '`@brust/runtime-dom`' : '(`@brust/runtime-dom` still private: dry run skipped)'} and six \`@brust/native-<plat>\` on \`workflow_dispatch\`; publishing stays tag-gated and human.`, '')
  return L.join('\n')
}
