//! jsx-rust-compiler — spike validation of the Path A JSX→Rust compiler pipeline.
//!
//! Goal: prove that we can ingest a `.tsx` file, parse it via swc, walk the
//! JSX AST, and emit Rust source code that uses the `maud` HTML DSL. This is
//! NOT a production compiler — it handles only the minimal JSX subset needed
//! to compile the spike input below.
//!
//! Usage:
//!   cd tools/jsx-rust-compiler
//!   cargo run -- <path-to-tsx-file>
//!
//! Outputs the emitted Rust source to stdout. The caller pastes it into
//! a real Rust project alongside `maud = "0.26"`, compiles + verifies.

use anyhow::{Result, anyhow};
use std::path::PathBuf;

use swc_core::common::errors::{ColorConfig, Handler};
use swc_core::common::sync::Lrc;
use swc_core::common::{FileName, SourceMap};
use swc_core::ecma::ast::*;
use swc_core::ecma::parser::{EsSyntax, Parser, StringInput, Syntax, TsSyntax, lexer::Lexer};

fn main() -> Result<()> {
    let path = std::env::args()
        .nth(1)
        .ok_or_else(|| anyhow!("usage: jsx-rust-compiler <file.tsx>"))?;

    let cm: Lrc<SourceMap> = Default::default();
    let _handler = Handler::with_tty_emitter(ColorConfig::Auto, true, false, Some(cm.clone()));

    let p = PathBuf::from(&path);
    let src = std::fs::read_to_string(&p)?;
    let fm = cm.new_source_file(FileName::Real(p).into(), src);

    let syntax = if path.ends_with(".tsx") || path.ends_with(".ts") {
        Syntax::Typescript(TsSyntax {
            tsx: path.ends_with(".tsx"),
            decorators: false,
            dts: false,
            no_early_errors: false,
            disallow_ambiguous_jsx_like: false,
        })
    } else {
        Syntax::Es(EsSyntax {
            jsx: true,
            ..Default::default()
        })
    };

    let lexer = Lexer::new(
        syntax,
        EsVersion::Es2022,
        StringInput::from(&*fm),
        None,
    );
    let mut parser = Parser::new_from(lexer);
    let module = parser
        .parse_module()
        .map_err(|e| anyhow!("parse failed: {:?}", e))?;

    let mut compiler = Compiler::new();
    compiler.compile_module(&module)?;
    print!("{}", compiler.out);
    Ok(())
}

struct Compiler {
    out: String,
    indent: usize,
}

impl Compiler {
    fn new() -> Self {
        Self {
            out: String::new(),
            indent: 0,
        }
    }

    fn push_indent(&mut self) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
    }

    fn writeln(&mut self, s: &str) {
        self.push_indent();
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn compile_module(&mut self, module: &Module) -> Result<()> {
        // Header
        self.out.push_str("// Generated by jsx-rust-compiler — do not edit by hand.\n");
        self.out.push_str("use maud::{Markup, html};\n\n");

        // Find `export default function NAME(...)`.
        let mut found_default = false;
        for item in &module.body {
            if let ModuleItem::ModuleDecl(ModuleDecl::ExportDefaultDecl(default)) = item {
                if let DefaultDecl::Fn(fn_expr) = &default.decl {
                    self.compile_default_fn(fn_expr)?;
                    found_default = true;
                    break;
                }
            }
        }
        if !found_default {
            // Fallback: any top-level function declaration.
            for item in &module.body {
                if let ModuleItem::Stmt(Stmt::Decl(Decl::Fn(fn_decl))) = item {
                    self.compile_fn_decl(fn_decl)?;
                    return Ok(());
                }
            }
            return Err(anyhow!(
                "no `export default function` or top-level function found",
            ));
        }
        Ok(())
    }

    fn compile_default_fn(&mut self, fn_expr: &FnExpr) -> Result<()> {
        let name = fn_expr
            .ident
            .as_ref()
            .map(|i| i.sym.as_ref().to_string())
            .unwrap_or_else(|| "Component".to_string());
        let snake = to_snake_case(&name);

        // Param destructuring → Props struct (minimal: assume one destructured object param).
        let mut prop_names: Vec<String> = Vec::new();
        if let Some(first) = fn_expr.function.params.first() {
            collect_prop_names(&first.pat, &mut prop_names);
        }

        // Emit Props struct (props are typed `&str` for simplicity in the spike).
        if !prop_names.is_empty() {
            self.writeln(&format!("pub struct {}Props<'a> {{", name));
            self.indent += 1;
            for p in &prop_names {
                self.writeln(&format!("pub {}: &'a str,", to_snake_case(p)));
            }
            self.indent -= 1;
            self.writeln("}");
            self.writeln("");
            self.writeln(&format!("pub fn render_{}(props: &{}Props) -> Markup {{", snake, name));
        } else {
            self.writeln(&format!("pub fn render_{}() -> Markup {{", snake));
        }
        self.indent += 1;
        self.writeln("html! {");
        self.indent += 1;

        // Walk function body, find first return statement with JSX.
        if let Some(body) = &fn_expr.function.body {
            for stmt in &body.stmts {
                if let Stmt::Return(ret) = stmt {
                    if let Some(arg) = &ret.arg {
                        self.compile_jsx_expr(arg, &prop_names)?;
                    }
                }
            }
        }

        self.indent -= 1;
        self.writeln("}");
        self.indent -= 1;
        self.writeln("}");
        Ok(())
    }

    fn compile_fn_decl(&mut self, fn_decl: &FnDecl) -> Result<()> {
        // Adapter: treat FnDecl like a FnExpr-ish default export.
        let fake = FnExpr {
            ident: Some(fn_decl.ident.clone()),
            function: fn_decl.function.clone(),
        };
        self.compile_default_fn(&fake)
    }

    fn compile_jsx_expr(&mut self, expr: &Expr, props: &[String]) -> Result<()> {
        match expr {
            Expr::Paren(p) => self.compile_jsx_expr(&p.expr, props),
            Expr::JSXElement(el) => self.compile_jsx_element(el, props),
            Expr::JSXFragment(f) => self.compile_jsx_children(&f.children, props),
            _ => {
                self.writeln("/* unsupported top-level expr */");
                Ok(())
            }
        }
    }

    fn compile_jsx_element(&mut self, el: &JSXElement, props: &[String]) -> Result<()> {
        let tag = match &el.opening.name {
            JSXElementName::Ident(i) => i.sym.as_ref().to_string(),
            _ => return Err(anyhow!("only simple-ident JSX tag names supported in spike")),
        };

        // Only lowercase tags map directly to maud HTML elements.
        // Uppercase = custom component — for the spike, emit a TODO comment.
        let is_custom = tag.chars().next().is_some_and(|c| c.is_uppercase());
        if is_custom {
            self.writeln(&format!("/* TODO: custom component <{}> — inline or codegen separately */", tag));
            // Still emit children so we don't drop content.
            if !el.children.is_empty() {
                self.compile_jsx_children(&el.children, props)?;
            }
            return Ok(());
        }

        let mut line = tag.clone();
        for attr in &el.opening.attrs {
            if let JSXAttrOrSpread::JSXAttr(a) = attr {
                let attr_name = match &a.name {
                    JSXAttrName::Ident(i) => match i.sym.as_ref() {
                        "className" => "class",
                        "htmlFor" => "for",
                        other => other,
                    }
                    .to_string(),
                    JSXAttrName::JSXNamespacedName(_) => continue,
                };
                match &a.value {
                    Some(JSXAttrValue::Lit(Lit::Str(s))) => {
                        line.push_str(&format!(" {}=\"{}\"", attr_name, s.value));
                    }
                    Some(JSXAttrValue::JSXExprContainer(JSXExprContainer {
                        expr: JSXExpr::Expr(e),
                        ..
                    })) => {
                        line.push_str(&format!(" {}=", attr_name));
                        line.push_str(&self.render_inline_expr(e, props));
                    }
                    None => {
                        // Boolean attribute (no value).
                        line.push_str(&format!(" {}", attr_name));
                    }
                    _ => {}
                }
            }
        }

        let self_closing = el.opening.self_closing || el.children.is_empty();
        if self_closing {
            self.writeln(&format!("{};", line));
        } else {
            self.writeln(&format!("{} {{", line));
            self.indent += 1;
            self.compile_jsx_children(&el.children, props)?;
            self.indent -= 1;
            self.writeln("}");
        }
        Ok(())
    }

    fn compile_jsx_children(&mut self, children: &[JSXElementChild], props: &[String]) -> Result<()> {
        for c in children {
            match c {
                JSXElementChild::JSXText(t) => {
                    // JSX text: collapse whitespace per JSX spec (rough).
                    let v: String = t.value.split_whitespace().collect::<Vec<_>>().join(" ");
                    if !v.is_empty() {
                        // Insert leading/trailing space markers if the original had them.
                        let leading = t.value.chars().next().is_some_and(char::is_whitespace);
                        let trailing = t.value.chars().last().is_some_and(char::is_whitespace);
                        let mut out = String::new();
                        if leading { out.push(' '); }
                        out.push_str(&v);
                        if trailing { out.push(' '); }
                        self.writeln(&format!("{:?}", out));
                    }
                }
                JSXElementChild::JSXExprContainer(JSXExprContainer {
                    expr: JSXExpr::Expr(e),
                    ..
                }) => {
                    let r = self.render_inline_expr(e, props);
                    self.writeln(&r);
                }
                JSXElementChild::JSXElement(el) => self.compile_jsx_element(el, props)?,
                JSXElementChild::JSXFragment(f) => self.compile_jsx_children(&f.children, props)?,
                _ => {}
            }
        }
        Ok(())
    }

    /// Render a JS expression inside an `{...}` JSX expression as a maud
    /// inline-interpolation `(expr)` string. Conservative — falls back to a
    /// `/* unsupported expr */` comment when we don't know how to translate.
    fn render_inline_expr(&self, e: &Expr, props: &[String]) -> String {
        match e {
            Expr::Ident(i) => {
                let n = i.sym.as_ref();
                // If the ident is one of the destructured props, rewrite as props.snake.
                if props.iter().any(|p| p == n) {
                    format!("(props.{})", to_snake_case(n))
                } else {
                    format!("({})", n)
                }
            }
            Expr::Lit(Lit::Str(s)) => format!("({:?})", s.value),
            Expr::Lit(Lit::Num(n)) => format!("({})", n.value),
            Expr::Member(m) => {
                let obj = self.render_inline_expr(&m.obj, props);
                if let MemberProp::Ident(i) = &m.prop {
                    // `(obj).field` → strip parens, attach .field.
                    let obj_inner = obj.trim_start_matches('(').trim_end_matches(')');
                    format!("({}.{})", obj_inner, i.sym.as_ref())
                } else {
                    "(/* unsupported member */)".to_string()
                }
            }
            Expr::Tpl(_) => "(/* TODO: template literal */)".to_string(),
            _ => "(/* unsupported expr */)".to_string(),
        }
    }
}

fn collect_prop_names(pat: &Pat, out: &mut Vec<String>) {
    if let Pat::Object(obj) = pat {
        for prop in &obj.props {
            match prop {
                ObjectPatProp::Assign(a) => out.push(a.key.sym.as_ref().to_string()),
                ObjectPatProp::KeyValue(kv) => {
                    if let PropName::Ident(i) = &kv.key {
                        out.push(i.sym.as_ref().to_string());
                    }
                }
                _ => {}
            }
        }
    }
}

fn to_snake_case(s: &str) -> String {
    let mut out = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() && i > 0 {
            out.push('_');
        }
        out.push(c.to_ascii_lowercase());
    }
    out
}
