//! Server backend (spec §6.4): the precompute job module — a pure function of
//! its declared inputs returning the `_sN` slots. Printed from the original
//! expressions (`to_js` server context), with the user's imports and module
//! helpers kept verbatim; state seeds and the derived values the slots reach
//! are `const`s in source order (M1c inputs 1–2).
use super::common::{Facts, import_lines, imports_in, module_code, module_names_in, server_js};
use crate::ir::{Attr, ComponentIR, Expr, IdentKind, JobKind, Node, RawExpr, expr::js_string};
use std::collections::BTreeSet;

/// One precompute slot: its expression and the lists it sits in (outermost first).
struct Slot {
    name: String,
    raw: RawExpr,
    lists: Vec<(RawExpr, String, Option<String>)>,
    /// Enclosing conditions (list depth, condition, negated): React never
    /// evaluates a branch it does not render, so neither does the job.
    guards: Vec<Guard>,
}

type Guard = (usize, RawExpr, bool);

/// Walk state: the enclosing lists and conditions.
#[derive(Default)]
struct Ctx {
    lists: Vec<(RawExpr, String, Option<String>)>,
    guards: Vec<Guard>,
}

pub fn job(ir: &ComponentIR) -> Option<String> {
    let job = ir
        .jobs
        .iter()
        .find(|j| matches!(j.kind, JobKind::Precompute))?;
    let structural = ir.structural.as_deref()?;
    let f = Facts::new(ir, structural);

    let mut slots: Vec<Slot> = Vec::new();
    collect(
        &ir.template,
        &structural.template,
        &mut Ctx::default(),
        &mut slots,
    );
    // Seeds and derived values that are slots read their own const.
    let mut slot_of_const: Vec<(String, String)> = Vec::new();
    for (s, ss) in ir.state.iter().zip(&structural.state) {
        if let (Expr::Precomputed { slot, .. }, Expr::Raw(_)) = (&s.init, &ss.init) {
            slot_of_const.push((slot.clone(), s.name.clone()));
        }
    }
    for d in &ir.derived {
        if let Expr::Precomputed { slot, .. } = &d.expr {
            slot_of_const.push((slot.clone(), d.name.clone()));
        }
    }

    // What the job runs: slots, every seed, and the derived values they reach.
    let inits: Vec<Option<RawExpr>> = (0..ir.state.len()).map(|i| f.state_init(i)).collect();
    let mut roots: Vec<&RawExpr> = slots.iter().map(|s| &s.raw).collect();
    for s in &slots {
        roots.extend(s.lists.iter().map(|l| &l.0));
        roots.extend(s.guards.iter().map(|g| &g.1));
    }
    roots.extend(inits.iter().flatten());
    let mut reached = f.reach(&roots);
    for (_, name) in &slot_of_const {
        if f.derived.contains_key(name) {
            reached.insert(name.clone());
            reached.extend(f.reach(&[f.derived_raw(name)?]));
        }
    }
    let derived: Vec<(&str, &RawExpr)> = structural
        .derived
        .iter()
        .filter(|d| reached.contains(&d.name))
        .filter_map(|d| f.derived_raw(&d.name).map(|r| (d.name.as_str(), r)))
        .collect();

    let mut imports = BTreeSet::new();
    let mut module_names = BTreeSet::new();
    let mut props = BTreeSet::new();
    for r in roots.iter().copied().chain(derived.iter().map(|d| d.1)) {
        imports_in(r, &mut imports);
        module_names_in(r, &f, &mut module_names);
        super::common::visit_idents(r, &mut |name, kind| {
            if *kind == IdentKind::Prop {
                props.insert(name.to_string());
            }
        });
    }
    let module = module_code(ir, &module_names, &mut imports);

    let mut out = format!(
        "// generated by brust v2 — precompute job for {}; pure function of its inputs\n",
        ir.id
    );
    out.push_str(&import_lines(&imports));
    out.push_str(&module);
    out.push_str(&format!(
        "export const inputs = [{}] as const\n",
        job.inputs
            .iter()
            .map(|i| js_string(i))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    out.push_str("export function precompute(props: any) {\n");
    // Props by local name (a renamed prop: `title: heading`).
    let mut fields = Vec::new();
    for p in &props {
        if p == "*" {
            continue;
        }
        let default = f
            .prop_defaults
            .get(p)
            .map(|d| format!(" = {}", server_js(d, &f)))
            .unwrap_or_default();
        match f.prop_locals.get(p) {
            Some(local) if local != p => fields.push(format!("{p}: {local}{default}")),
            _ => fields.push(format!("{p}{default}")),
        }
    }
    if props.contains("*")
        && let Some(local) = f.prop_locals.get("*")
        && local != "props"
    {
        out.push_str(&format!("  const {local} = props\n"));
    }
    if !fields.is_empty() {
        out.push_str(&format!("  const {{ {} }} = props\n", fields.join(", ")));
    }
    let mut decls: Vec<(u32, String)> = Vec::new();
    for (i, s) in ir.state.iter().enumerate() {
        if let Some(r) = &inits[i] {
            let loc = structural.state[i].init.raw_loc().unwrap_or_default();
            decls.push((loc, format!("const {} = {}", s.name, server_js(r, &f))));
        }
    }
    for (name, r) in &derived {
        decls.push((r.loc, format!("const {name} = {}", server_js(r, &f))));
    }
    decls.sort_by_key(|d| d.0);
    for (_, line) in decls {
        out.push_str(&format!("  {line}\n"));
    }
    let mut entries: Vec<(u32, String)> = Vec::new();
    for s in &slots {
        let guard = |js: String, level: usize| -> String {
            let conds: Vec<String> = s
                .guards
                .iter()
                .filter(|g| g.0 == level)
                .map(|(_, c, neg)| {
                    let c = server_js(c, &f);
                    if *neg {
                        format!("!({c})")
                    } else {
                        format!("({c})")
                    }
                })
                .collect();
            if conds.is_empty() {
                js
            } else {
                format!("({} ? {js} : undefined)", conds.join(" && "))
            }
        };
        let mut js = guard(server_js(&s.raw, &f), s.lists.len());
        for (level, (src, item, index)) in s.lists.iter().enumerate().rev() {
            let params = match index {
                Some(i) => format!("{item}, {i}"),
                None => item.clone(),
            };
            js = guard(
                format!("({}).map(({params}) => {js})", server_js(src, &f)),
                level,
            );
        }
        entries.push((slot_num(&s.name), format!("{}: {js}", s.name)));
    }
    for (slot, name) in &slot_of_const {
        entries.push((slot_num(slot), format!("{slot}: {name}")));
    }
    entries.sort_by_key(|e| e.0);
    out.push_str(&format!(
        "  return {{ {} }}\n}}\n",
        entries
            .into_iter()
            .map(|e| e.1)
            .collect::<Vec<_>>()
            .join(", ")
    ));
    Some(out)
}

fn slot_num(s: &str) -> u32 {
    s.trim_start_matches("_s").parse().unwrap_or(0)
}

fn collect(n: &Node, s: &Node, cx: &mut Ctx, out: &mut Vec<Slot>) {
    let expr = |e: &Expr, se: &Expr, cx: &Ctx, out: &mut Vec<Slot>| {
        if let (Expr::Precomputed { slot, per_item, .. }, Expr::Raw(r)) = (e, se) {
            let (lists, guards) = if per_item.is_some() {
                (cx.lists.clone(), cx.guards.clone())
            } else {
                // A slot outside its lists is evaluated at the top level.
                (
                    Vec::new(),
                    cx.guards.iter().filter(|g| g.0 == 0).cloned().collect(),
                )
            };
            out.push(Slot {
                name: slot.clone(),
                raw: r.clone(),
                lists,
                guards,
            });
        }
    };
    match (n, s) {
        (
            Node::Element {
                attrs, children, ..
            },
            Node::Element {
                attrs: sa,
                children: sc,
                ..
            },
        ) => {
            for (a, b) in attrs.iter().zip(sa) {
                if let (
                    Attr::Dynamic { value, .. } | Attr::Spread(value),
                    Attr::Dynamic { value: sv, .. } | Attr::Spread(sv),
                ) = (a, b)
                {
                    expr(value, sv, cx, out);
                }
            }
            for (c, d) in children.iter().zip(sc) {
                collect(c, d, cx, out);
            }
        }
        (Node::Slot(e), Node::Slot(se)) => expr(e, se, cx, out),
        (
            Node::If { cond, then, else_ },
            Node::If {
                cond: sc,
                then: st,
                else_: se,
            },
        ) => {
            expr(cond, sc, cx, out);
            let level = cx.lists.len();
            let cond_raw = match sc {
                Expr::Raw(r) => Some(r.clone()),
                _ => None,
            };
            for (branch, sbranch, negate) in [(then, st, false), (else_, se, true)] {
                if let Some(c) = &cond_raw {
                    cx.guards.push((level, c.clone(), negate));
                }
                for (c, d) in branch.iter().zip(sbranch) {
                    collect(c, d, cx, out);
                }
                if cond_raw.is_some() {
                    cx.guards.pop();
                }
            }
        }
        (
            Node::For {
                source,
                item,
                index,
                key,
                body,
            },
            Node::For {
                source: ss,
                key: sk,
                body: sb,
                ..
            },
        ) => {
            expr(source, ss, cx, out);
            if let Expr::Raw(sr) = ss {
                cx.lists.push((sr.clone(), item.clone(), index.clone()));
                expr(key, sk, cx, out);
                for (c, d) in body.iter().zip(sb) {
                    collect(c, d, cx, out);
                }
                cx.lists.pop();
            }
        }
        (
            Node::Component {
                props, children, ..
            },
            Node::Component {
                props: sp,
                children: sc,
                ..
            },
        ) => {
            for ((_, v), (_, sv)) in props.iter().zip(sp) {
                expr(v, sv, cx, out);
            }
            for (c, d) in children.iter().zip(sc) {
                collect(c, d, cx, out);
            }
        }
        (Node::Fragment(cs), Node::Fragment(ss)) => {
            for (c, d) in cs.iter().zip(ss) {
                collect(c, d, cx, out);
            }
        }
        _ => {}
    }
}
