// generated by brust v2 — client chunk for input_7a17a8db
import { signal, computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_7a17a8db", ({ el, props, effect, onCleanup, ref }) => {
  const mode = signal("dark")
  const label = computed(() => mode() === "dark" ? "Light" : "Dark")
  const _h1 = (...a) => (() => mode.set((m) => m === "dark" ? "light" : "dark"))(...a)
  const _c1 = computed(() => props().themeLabel)
  const _c2 = computed(() => label())
  effect(() => (((mode) => (() => {
  document.documentElement.dataset.mode = mode;
}))(mode()))())
  return { mode, _h1, _c1, _c2 }
})
