// generated by brust v2 — client chunk for input_7a17a8db
import { signal, computed, untracked, defineBehavior } from "brust/runtime-dom"
const __attr = (v) => (v === false ? null : v)
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("input_7a17a8db", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const mode = signal("dark")
  const label = computed(() => mode() === "dark" ? "Light" : "Dark")
  const _h1 = (...a) => (() => mode.set((m) => m === "dark" ? "light" : "dark"))(...a)
  const _c1 = computed(() => __attr(props().themeLabel))
  const _c2 = computed(() => __text(label()))
  __effect(() => { void [mode()]; return untracked(() => (((mode) => (() => {
  document.documentElement.dataset.mode = mode;
}))(mode()))()) })
  return { mode, _h1, _c1, _c2 }
})
