// generated by brust v2 — client chunk for input_04b8b787
import { computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_04b8b787", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _l1 = computed(() => props().fields)
  const _k1 = (f) => f.key
  const _p1 = (f) => ({ label: f.label })
  return { _l1, _k1, _p1 }
})
