// generated by brust v2 — client chunk for field_603ad356
import { signal, computed, defineBehavior } from "brust/runtime-dom"
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("field_603ad356", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const id = JSON.parse(__el.getAttribute("x-props") ?? "{}")._id0
  const v = signal("")
  const _h1 = (...a) => ((e) => v.set(e.target.value))(...a)
  const _c1 = computed(() => __text(props().label))
  return { v, _h1, _c1 }
})
