// generated by brust v2 — precompute job for input_f5cee24e; pure function of its inputs
import { formatPrice } from "./money"
export const inputs = ["item.price"] as const
export function precompute(props: any) {
  const { item } = props
  return { _s1: formatPrice(item.price) }
}
