// generated by brust v2 — client chunk for input_2b13db9f
import { signal, computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_2b13db9f", ({ el, props, effect, onCleanup, ref }) => {
  const q = signal("")
  const _h1 = (...a) => ((e) => q.set(e.target.value))(...a)
  const _c1 = computed(() => props().placeholder)
  const _c2 = computed(() => q().length > 0)
  const _c3 = computed(() => q())
  return { q, _h1, _c1, _c2, _c3 }
})
