// generated by brust v2 — client chunk for priceRow_845bcd56
import { defineBehavior } from "brust/runtime-dom"
export default defineBehavior("priceRow_845bcd56", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  return {  }
})
