// generated by brust v2 — precompute job for priceRow_845bcd56; pure function of its inputs
import { fmt } from "./money"
export const inputs = ["item.price", "unit"] as const
export function precompute(props: any) {
  const { item, unit } = props
  return { _s1: fmt(item.price, unit) }
}
