// generated by brust v2 — client chunk for input_7833a2e1
import { computed, defineBehavior } from "brust/runtime-dom"
export default defineBehavior("input_7833a2e1", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _l1 = computed(() => props().items)
  const _k1 = (it) => it.id
  const _p1 = (it) => ({ item: it, unit: props().unit })
  return { _l1, _k1, _p1 }
})
