// generated by brust v2 — client chunk for input_38302085
import { signal, computed, defineBehavior } from "brust/runtime-dom"
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("input_38302085", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const open = signal(false)
  const n = signal(5)
  const list = signal([])
  const _h1 = (...a) => (() => open.set(!open()))(...a)
  const _c1 = computed(() => open())
  const _c2 = computed(() => __text(open() && "text-branch"))
  const _c3 = computed(() => list())
  const _p1 = computed(() => ({ start: n() }))
  const _p2 = computed(() => ({ start: n() * 2 }))
  return { open, n, list, _h1, _c1, _c2, _c3, _p1, _p2 }
})
