// The M1 exit report (spec §12): counts from the battery plus the declared and
// battery-found gaps. Deterministic: derived from the same results as the
// coverage report, no timestamps.
import { CATEGORIES, type Expect } from './rows.ts'
import type { Result } from './run.ts'

/** Rows whose observed tier is accepted to differ from (or whose checks are relaxed against) the spec, by ledger id. Set-equal to the rows carrying `knownGap`. */
export const KNOWN_GAP_ROWS: Record<string, { ledger: string; observed: Expect }> = {
  'a-nested-list': { ledger: 'F32', observed: 'static' },
  'e-if-in-table': { ledger: 'F32', observed: 'native' },
  'b-memo': { ledger: 'F37', observed: 'react' },
  'c-useid': { ledger: 'F39', observed: 'react' },
}
/** Rows that must produce an `Error` diagnostic and refuse to build. */
export const ERROR_ROWS = ['e-function-prop-react-child', 'e-server-only-handler', 'e-request-prop', 'e-missing-key'] as const
export const COMPILE_ERROR_ROWS = ['e-parse-error'] as const

/** Gaps declared by the plans (ledger ids in docs/plans/m1a-followups.md). */
export const DECLARED_GAPS: { id: string; what: string; owner: string }[] = [
  { id: 'F32', what: '`<brust-if>` / `<brust-row>` wrappers inside `<table>` / `<select>` / `<ul>` are foster-parented by the HTML parser, so the DOM differs from the jinja text', owner: 'M2' },
  { id: 'F33', what: 'a truthiness guard on a prop (`user && …`) contributes only its member reads to the job inputs, so `null` and `{}` share a cache key', owner: 'M2' },
  { id: 'F34', what: 'an inlined child with its own precompute job needs per-instance child jobs, which need the M2 server', owner: 'M2' },
  { id: 'F35', what: 'dynamic `<script>` / `<style>` children are HTML-escaped inside raw text (safe, but the value changes silently)', owner: 'M2' },
]

/** Gaps the battery itself found (ledger ids F37, F39, F40; F38 was fixed by `m1-hotfix-dynamic-import`). */
export const BATTERY_GAPS: { id: string; what: string }[] = [
  { id: 'F37', what: '`memo(Inner)` default exports are not unwrapped: tier `react` (`default-export-shape`) where the plan expected `native`' },
  { id: 'F39', what: 'a `useId` value read in render falls back (`use-id-in-render`); the spec §4.3 row `useId` needs server-generated ids from the M2 server (spec §13 (a); `docs/plans/2026-10-08-m1b2-placement-tier.md:206`)' },
  { id: 'F40', what: 'the `Array.from(xs, fn)` callback form is not recognised (only `Array.from({ length: N }).map(…)` is, spec §6.2): tier `react` (`jsx-expression`)' },
]

export const BROWSER_CASES = ['theme-toggle', 'product-card', 'parent-counter', 'keyed-list', 'keyed-list-child', 'controlled-input', 'nested-list', 'truthiness']

export function renderExitReport(results: Result[]): string {
  const n = (f: (r: Result) => boolean) => results.filter(f).length
  const L: string[] = []
  L.push('# M1 exit report', '')
  L.push('Generated by `bun run battery`; do not edit. Criteria are spec §12; `bun test scripts/battery/exit.test.ts` checks them by code.', '')
  L.push('## Battery', '')
  L.push(`- ${results.length} rows compiled through the real \`brustc\`: ${n((r) => r.observed === 'static')} static, ${n((r) => r.observed === 'native')} native, ${n((r) => r.observed === 'react')} react, ${n((r) => r.observed === 'error')} error, ${n((r) => r.observed === 'compile-error')} compile error.`)
  L.push(`- Unexplained disagreements with the spec: ${n((r) => r.warn)}. Documented known gaps: ${n((r) => !!r.row.knownGap)} rows.`)
  for (const [cat, title] of Object.entries(CATEGORIES)) {
    const rs = results.filter((r) => r.row.category === cat)
    L.push(`- ${cat} ${title}: ${rs.length} rows (${rs.filter((r) => r.observed === 'static' || r.observed === 'native').length} compile native/static, ${rs.filter((r) => r.observed === 'react').length} react, ${rs.filter((r) => r.observed === 'error' || r.observed === 'compile-error').length} error)`)
  }
  const gaps = results.filter((r) => r.row.knownGap).map((r) => r.row.id).join(', ')
  L.push('', `§12 reading: every row this design says is native/static compiles so, **except the known-gap rows** (${gaps}; ledger F32, F37, F39); every other non-native row is \`react\` with a fallback diagnostic and no build error, **except the deliberate rows** that exercise errors (\`error\`: Error diagnostics by design) and the unparseable snippet (\`compile error\`, which never aborts the battery). F38 (a dynamic \`import()\` crashed the printer) is fixed. \`Error\` rows carry an \`Error\` diagnostic. See \`docs/react-coverage.md\` for the rows.`, '')
  L.push('## Dual evaluation', '', '`cargo test -p brust-compiler --test dual_eval`: for every fixture with sample props, the server paint equals the client initial values.', '')
  L.push('## Browser harness', '', 'The example components of the design doc, built by `brustc --emit all`, painted by `brustc --render`, mounted with `packages/runtime-dom` (`bun run browser-test`):', '')
  for (const c of BROWSER_CASES) L.push(`- ${c}`)
  L.push('', 'Each case asserts first-paint equality (no runtime warning, no visible DOM change on mount) and its interactions.', '')
  L.push('## Known gaps', '', '| Id | Gap | Owner |', '|---|---|---|')
  for (const g of DECLARED_GAPS) L.push(`| ${g.id} | ${g.what} | ${g.owner} |`)
  for (const g of BATTERY_GAPS) L.push(`| ${g.id} | ${g.what} | ledger |`)
  L.push('')
  return L.join('\n')
}
