// The M1 exit report (spec §12): counts from the battery plus the declared and
// battery-found gaps. Deterministic: derived from the same results as the
// coverage report, no timestamps.
import { CATEGORIES, type Expect } from './rows.ts'
import type { Result } from './run.ts'

/** Rows whose observed tier is accepted to differ from (or whose checks are relaxed against) the spec, by ledger id. Set-equal to the rows carrying `knownGap`. */
export const KNOWN_GAP_ROWS: Record<string, { ledger: string; observed: Expect }> = {}
/** Rows that must produce an `Error` diagnostic and refuse to build. */
export const ERROR_ROWS = ['e-function-prop-react-child', 'e-server-only-handler', 'e-request-prop', 'e-missing-key'] as const
export const COMPILE_ERROR_ROWS = ['e-parse-error'] as const

/** Gaps still open after `m2a-compiler` (ledger ids in docs/plans/m1a-followups.md). F33, F35, F37, F39, F40 and F32 (single-root) are closed. */
export const DECLARED_GAPS: { id: string; what: string; owner: string }[] = [
  { id: 'F32-b', what: 'an `x-if` branch that is one inlined component keeps its `<brust-if>` wrapper (the runtime skips a host before `x-if`, ledger F52), and multi-root rows/branches keep theirs: foster-parented inside `<table>` / `<select>`', owner: 'm2d / M3' },
  { id: 'F34', what: 'per-instance child jobs: the compiler half is done (`instances[]` in the IR); running them per row needs the M2 server', owner: 'm2b' },
]

/** Gaps the battery itself found: none open (F37, F39, F40 closed by `m2a-compiler`; F38 by `m1-hotfix-dynamic-import`). */
export const BATTERY_GAPS: { id: string; what: string }[] = []

export const BROWSER_CASES = ['theme-toggle', 'product-card', 'parent-counter', 'keyed-list', 'keyed-list-child', 'controlled-input', 'nested-list', 'truthiness', 'table-rows', 'guarded-slot']

/** Rust-side pins of `crates/brust-compiler/tests/dual_eval.rs`; keep in sync with dual_eval.rs. */
export const DUAL_EVAL_NO_SAMPLES = ['arrow-default', 'client-only', 'fragment-root', 'import-cycle', 'jsx-shapes', 'lazy-import', 'missing-key', 'react-child', 'react-hook', 'server-leak']
export const DUAL_EVAL_NO_DIRECTIVES = ['static-text', 'cached-card', 'outlet-layout', 'keyed-list-child-job', 'static-list-child']

export function renderExitReport(results: Result[]): string {
  const n = (f: (r: Result) => boolean) => results.filter(f).length
  const L: string[] = []
  L.push('# M1 exit report', '')
  L.push('Generated by `bun run battery`; do not edit. Criteria are spec §12; `bun test scripts/battery/exit.test.ts` checks them by code.', '')
  L.push('## Battery', '')
  L.push(`- ${results.length} rows analysed by the real \`brustc --emit ir\`: ${n((r) => r.observed === 'static')} static, ${n((r) => r.observed === 'native')} native, ${n((r) => r.observed === 'react')} react, ${n((r) => r.observed === 'error')} error, ${n((r) => r.observed === 'compile-error')} compile error.`)
  const lowered = results.filter((r) => r.built)
  L.push(`- Build: ${lowered.length} rows lowered with \`--emit all\`: ${lowered.filter((r) => r.build === 'ok').length} ok, ${lowered.filter((r) => r.build === 'refused').length} refused (error rows), ${lowered.filter((r) => r.build === 'failed').length} failed. ${results.length - lowered.length} row(s) never reached lowering (compile error).`)
  L.push(`- Unexplained disagreements with the spec: ${n((r) => r.warn)}. Documented known gaps: ${n((r) => !!r.row.knownGap)} rows.`)
  for (const [cat, title] of Object.entries(CATEGORIES)) {
    const rs = results.filter((r) => r.row.category === cat)
    L.push(`- ${cat} ${title}: ${rs.length} rows (${rs.filter((r) => r.observed === 'static' || r.observed === 'native').length} compile native/static, ${rs.filter((r) => r.observed === 'react').length} react, ${rs.filter((r) => r.observed === 'error').length} error, ${rs.filter((r) => r.observed === 'compile-error').length} compile error)`)
  }
  const gapIds = Object.keys(KNOWN_GAP_ROWS)
  const gaps = gapIds.map((id) => `${id} [${KNOWN_GAP_ROWS[id]!.ledger}: ${KNOWN_GAP_ROWS[id]!.observed}]`).join(', ')
  const ledgers = [...new Set(Object.values(KNOWN_GAP_ROWS).map((g) => g.ledger))].join(', ')
  const gapClause = gapIds.length ? `, **except the pinned known-gap rows** (${gaps}; ledger ${ledgers})` : ' (no known-gap rows)'
  const errRows = results.filter((r) => (ERROR_ROWS as readonly string[]).includes(r.row.id))
  const unrefused = errRows.filter((r) => r.build !== 'refused').map((r) => r.row.id)
  const errSentence = unrefused.length === 0
    ? `${errRows.length} deliberate \`error\` rows, each refused to build`
    : `${errRows.length} deliberate \`error\` rows, NOT refused: ${unrefused.join(', ')}`
  L.push('', `§12 reading: every row this design says is native/static compiles so${gapClause}; every other non-native row is \`react\` with a fallback diagnostic, **except** ${errSentence}, and ${COMPILE_ERROR_ROWS.length} unparseable snippet (\`compile error\`, which never aborts the battery). F38 (a dynamic \`import()\` crashed the printer) is fixed. See \`docs/react-coverage.md\` for the rows.`, '')
  L.push('## Dual evaluation', '', '`cargo test -p brust-compiler --test dual_eval`: for every fixture with sample props, the server paint equals the client initial values, and the number of server-painted `x-for` rows equals the client list length.', '')
  L.push('## Browser harness', '', 'The example components of the design doc, built by `brustc --emit all`, painted by `brustc --render`, mounted with `packages/runtime-dom` (`bun run browser-test`):', '')
  for (const c of BROWSER_CASES) L.push(`- ${c}`)
  L.push('', 'Each case asserts first-paint equality (no `console.warn` / `console.error`, no visible DOM change on mount), its interactions, and that the interactions raised no warning. `harness-self-test` is the harness\'s negative control.', '')
  L.push('## Verification', '', 'What each gate checks (the pinned sets are compared by set equality, so changing one changes a test):', '')
  L.push(`- Battery (\`scripts/battery/exit.test.ts\`): no row disagrees with its expected tier or job count unless it is in \`KNOWN_GAP_ROWS\` (${gapIds.join(', ') || 'empty'}), each of which must still observe its pinned tier${gapIds.length ? '' : ' (none today)'}; \`ERROR_ROWS\` (${ERROR_ROWS.join(', ')}) are the only rows expecting \`error\` and each must be refused; \`COMPILE_ERROR_ROWS\` (${COMPILE_ERROR_ROWS.join(', ')}); every row that reaches lowering must not \`fail\`; every \`react\` row carries a fallback diagnostic and no error.`)
  L.push(`- Dual evaluation (\`dual_eval.rs\`): fails without \`bun\` (\`BRUST_DUAL_EVAL_SKIP=1\` is local-only); fixtures without samples are pinned in \`NO_SAMPLES\` (${DUAL_EVAL_NO_SAMPLES.join(', ')}); sampled fixtures with nothing to compare are pinned in \`NO_DIRECTIVES\` (${DUAL_EVAL_NO_DIRECTIVES.join(', ')}); every other sampled fixture contributes at least one check.`)
  L.push(`- Browser (\`tests/browser\`, happy-dom): ${BROWSER_CASES.length} example cases plus the harness self-test, run as separate files by the exit test.`)
  L.push('', '## Known gaps', '', '| Id | Gap | Owner |', '|---|---|---|')
  for (const g of DECLARED_GAPS) L.push(`| ${g.id} | ${g.what} | ${g.owner} |`)
  for (const g of BATTERY_GAPS) L.push(`| ${g.id} | ${g.what} | ledger |`)
  L.push('')
  return L.join('\n')
}
