// Compiles every battery row through the real `brustc` and writes the
// deterministic report `docs/react-coverage.md`.
//   bun scripts/battery/run.ts            regenerate the report (exit 1 on an unexplained ⚠)
//   bun scripts/battery/run.ts --check    same, without writing
import { spawnSync } from 'node:child_process'
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, readFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { CATEGORIES, rows, type Expect, type Row } from './rows.ts'

const repo = resolve(import.meta.dir, '../..')
export const REPORT = join(repo, 'docs/react-coverage.md')

export interface Result {
  row: Row
  observed: Expect
  jobs: string[]
  diagnostics: string[]
  message?: string
  /** expectation not met (tier or job count), and the row is not a known gap */
  warn: boolean
}

export function buildBrustc(): string {
  const r = spawnSync('cargo', ['build', '-q', '-p', 'brust-compiler-cli'], { cwd: repo, stdio: ['ignore', 'inherit', 'inherit'] })
  if (r.status !== 0) throw new Error('cargo build -p brust-compiler-cli failed')
  return join(process.env.CARGO_TARGET_DIR ?? join(repo, 'target'), 'debug/brustc')
}

type Diag = { class: string; rule: string }
type IR = { tier: string | { React: unknown }; jobs: { kind: string | Record<string, unknown> }[]; diagnostics: Diag[] }

function compile(brustc: string, row: Row): Omit<Result, 'warn'> {
  const dir = mkdtempSync(join(tmpdir(), 'battery-'))
  try {
    writeFileSync(join(dir, 'input.tsx'), row.snippet + '\n')
    for (const [name, text] of Object.entries(row.files ?? {})) {
      mkdirSync(dirname(join(dir, name)), { recursive: true })
      writeFileSync(join(dir, name), text + '\n')
    }
    const p = spawnSync(brustc, ['input.tsx', '--emit', 'ir'], { cwd: dir, encoding: 'utf8' })
    if (p.status !== 0 || !p.stdout.trim().startsWith('{')) {
      // A snippet that does not parse is a result, not a crash.
      const lines = (p.stderr || p.stdout).split('\n').filter((l) => l.trim())
      // A compiler panic names a machine path on its first line: keep the assertion only.
      const message = lines[0]!.includes('panicked')
        ? `compiler panic: ${lines[1] ?? ''}`
        : lines[0]!.replace(/^error:\s*/, '').replaceAll(dir, '.')
      return { row, observed: 'compile-error', jobs: [], diagnostics: [], message }
    }
    const ir = JSON.parse(p.stdout) as IR
    const diagnostics = [...new Set(ir.diagnostics.map((d) => `${d.class.toLowerCase()}:${d.rule}`))]
    const hasError = ir.diagnostics.some((d) => d.class === 'Error')
    const tier = typeof ir.tier === 'string' ? (ir.tier.toLowerCase() as Expect) : 'react'
    const jobs = ir.jobs.map((j) => (typeof j.kind === 'string' ? j.kind : Object.keys(j.kind)[0]!).toLowerCase())
    return { row, observed: hasError ? 'error' : tier, jobs, diagnostics }
  } finally {
    rmSync(dir, { recursive: true, force: true })
  }
}

export function runBattery(): Result[] {
  const brustc = buildBrustc()
  return rows.map((row) => {
    const r = compile(brustc, row)
    const jobMiss = row.jobs !== undefined && row.jobs !== r.jobs.length
    return { ...r, warn: !row.knownGap && (r.observed !== row.expect || jobMiss) }
  })
}

const cell = (s: string) => s.replaceAll('|', '\\|')
const jobsCell = (j: string[]) => (j.length ? j.join(', ') : '0')

export function renderReport(results: Result[]): string {
  const version = /^version\s*=\s*"([^"]+)"/m.exec(readFileSync(join(repo, 'Cargo.toml'), 'utf8'))?.[1] ?? '?'
  const L: string[] = []
  L.push('# React coverage (v2)', '')
  L.push(`Generated by \`bun run battery\` (compiler ${version}); do not edit. Each row is compiled by the real \`brustc --emit ir\`.`)
  L.push('Expected tiers come from the design spec (§3 tier table, §4.3 hook table, §8.1 diagnostics). `⚠` = observed differs from expected (fails the battery); `known gap` = a documented disagreement.', '')
  L.push('## Summary', '')
  L.push('| Category | Rows | static | native | react | error | compile error | ⚠ |', '|---|---|---|---|---|---|---|---|')
  const total = { n: 0, static: 0, native: 0, react: 0, error: 0, ce: 0, warn: 0 }
  for (const [cat, title] of Object.entries(CATEGORIES)) {
    const rs = results.filter((r) => r.row.category === cat)
    const c = (o: Expect) => rs.filter((r) => r.observed === o).length
    const warn = rs.filter((r) => r.warn).length
    L.push(`| ${cat} ${title} | ${rs.length} | ${c('static')} | ${c('native')} | ${c('react')} | ${c('error')} | ${c('compile-error')} | ${warn} |`)
    Object.assign(total, {
      n: total.n + rs.length, static: total.static + c('static'), native: total.native + c('native'),
      react: total.react + c('react'), error: total.error + c('error'), ce: total.ce + c('compile-error'), warn: total.warn + warn,
    })
  }
  L.push(`| **Total** | ${total.n} | ${total.static} | ${total.native} | ${total.react} | ${total.error} | ${total.ce} | ${total.warn} |`, '')
  for (const [cat, title] of Object.entries(CATEGORIES)) {
    L.push(`## ${cat}. ${title}`, '')
    L.push('| Pattern | Authoring | Expected | Observed tier | Jobs | Diagnostics | Note |', '|---|---|---|---|---|---|---|')
    for (const r of results.filter((x) => x.row.category === cat)) {
      const observed = `${r.warn ? '⚠ ' : ''}${r.observed}`
      const note = [r.message ? `compile error: ${r.message}` : '', r.row.note ?? '', r.row.knownGap ? `known gap: ${r.row.knownGap}` : '']
        .filter(Boolean).join('; ')
      L.push(`| ${r.row.id} | ${cell(r.row.authoring)} | ${r.row.expect} | ${observed} | ${jobsCell(r.jobs)} | ${cell(r.diagnostics.join(', ') || '—')} | ${cell(note)} |`)
    }
    L.push('')
  }
  return L.join('\n')
}

if (import.meta.main) {
  const results = runBattery()
  const report = renderReport(results)
  if (!process.argv.includes('--check')) writeFileSync(REPORT, report)
  const bad = results.filter((r) => r.warn)
  for (const r of bad) console.error(`⚠ ${r.row.id}: expected ${r.row.expect}${r.row.jobs !== undefined ? ` (${r.row.jobs} jobs)` : ''}, observed ${r.observed} (${r.jobs.length} jobs) ${r.diagnostics.join(',')}`)
  console.log(`[battery] ${results.length} rows, ${bad.length} unexplained ⚠${process.argv.includes('--check') ? '' : ' -> docs/react-coverage.md'}`)
  process.exit(bad.length ? 1 : 0)
}
