// generated by brust v2 — client chunk for input_23089a0b
import { signal, computed, defineBehavior } from "brust/runtime-dom"
const __attr = (v) => (v === false ? null : v)
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("input_23089a0b", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const open = signal(false)
  const _h1 = (...a) => (() => open.set(!open()))(...a)
  const _c1 = computed(() => __attr(props().lang))
  const _c2 = computed(() => __text(props().title))
  const _c3 = computed(() => __attr(open() ? "yes" : "no"))
  const _c4 = computed(() => __text(props().title))
  return { open, _h1, _c1, _c2, _c3, _c4 }
})
