// generated by brust v2 — client chunk for input_6af673af
import { signal, computed, defineBehavior } from "brust/runtime-dom"
import { formatPrice } from "./money"
export default defineBehavior("input_6af673af", ({ el, props, effect, onCleanup, ref }) => {
  const qty = signal(1)
  const total = computed(() => formatPrice(props().item.price * qty()))
  const _h1 = (...a) => (() => qty.set(qty() + 1))(...a)
  const _c1 = computed(() => props().item.name)
  const _c2 = computed(() => total())
  return { qty, _h1, _c1, _c2 }
})
