// generated by brust v2 — precompute job for input_6af673af; pure function of its inputs
import { formatPrice } from "./money"
export const inputs = ["item.price"] as const
export function precompute(props: any) {
  const { item } = props
  const qty = 1
  const unit = formatPrice(item.price)
  const total = formatPrice(item.price * qty)
  return { _s1: unit, _s2: total }
}
