// generated by brust v2 — client chunk for card_eb22a07c
import { computed, defineBehavior } from "brust/runtime-dom"
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("card_eb22a07c", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _c1 = computed(() => __text(props().name))
  const _l1 = computed(() => props().tags)
  const _k1 = (t) => t
  const _p1 = (t) => ({ label: t })
  return { _c1, _l1, _k1, _p1 }
})
