// generated by brust v2 — client chunk for badge_18597abf
import { computed, defineBehavior } from "brust/runtime-dom"
const __text = (v) => (typeof v === "boolean" ? "" : Array.isArray(v) ? v.map(__text).join("") : v)
export default defineBehavior("badge_18597abf", ({ el: __el, props, effect: __effect, onCleanup: __onCleanup, ref: __ref }) => {
  const _c1 = computed(() => __text(props().label))
  return { _c1 }
})
